export const RECOMMENDED_CONTENT_CLASSES = {
  root: String.raw`file-page__recommended tw:[--card-title-section-body-list-display:none] tw:ml-app-l tw:w-[32rem] tw:[.main--video-page_&]:min-w-0 tw:[.main--video-page_&]:ml-0 tw:[.main--video-page_&]:w-full tw:fullscreen-side-panel:min-w-0 tw:fullscreen-side-panel:ml-0 tw:fullscreen-side-panel:w-full tw:[&_.card\_\_first-pane_.card\_\_header--between]:mb-app-m tw:[&_.card\_\_first-pane_.card\_\_body.card\_\_body--list]:[border-top:unset] tw:[&_.card\_\_header--between]:[align-items:unset] tw:[&_.card\_\_header--between_.card\_\_title-section--body-list]:mt-auto tw:[&_.claim-preview-metadata]:max-w-full tw:[&_.claim-preview-metadata_.claim-tile\_\_info]:max-w-full tw:[&_.claim-preview-metadata_.media\_\_subtitle]:max-w-full tw:[&_.claim-preview-metadata_.media\_\_subtitle_.button]:max-w-full tw:[&_.claim-preview-metadata_.media\_\_subtitle_.button-surface\_\_content]:max-w-full tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name]:max-w-full tw:[&_.claim-preview-metadata_.claim-tile\_\_info]:mt-0 tw:[&_.claim-preview-metadata_.media\_\_subtitle_.button-surface\_\_content]:mt-0 tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name]:mt-0 tw:[&_.claim-preview-metadata_.media\_\_subtitle_.date_time]:mt-0 tw:[&_.claim-preview-metadata_.media\_\_subtitle>span]:mt-0 tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name_p]:inline-block tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name_p]:max-w-[180px] tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name_p]:overflow-hidden tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name_p]:text-ellipsis tw:[&_.claim-preview-metadata_.media\_\_subtitle_.channel-name_p]:whitespace-nowrap tw:[&_.claim-preview-metadata_.claim-preview\_\_title_.truncated-text]:![-webkit-line-clamp:2] tw:[&_.claim-preview-metadata_.channel-thumbnail]:!hidden tw:[&_.claim-preview-metadata_.channel-thumbnail]:!size-[1.4rem] tw:upto-medium:mt-app-l tw:upto-medium:ml-0 tw:upto-medium:w-full tw:upto-small:[&_.claim-preview-metadata_.card\_\_header--between]:p-app-xxs tw:upto-small:[&_.claim-preview-metadata_.card\_\_header--between]:pb-app-s tw:upto-small:[&_.claim-preview-metadata_.card\_\_header--between]:pl-0`,
  bubble: String.raw`recommended-content__bubble tw:flex tw:items-center tw:[&_.icon--langFilter]:mr-app-s tw:[&_.button-toggle-surface:nth-child(2)]:ml-[2px] tw:small:[&_.button-toggle-surface:nth-child(2)]:mr-app-xs`,
  button: String.raw`button-bubble tw:mr-app-xxs tw:inline-flex tw:h-[2rem] tw:max-w-[15rem] tw:items-center tw:justify-center tw:rounded-[1rem] tw:!bg-[var(--color-button-toggle-bg)] tw:px-app-xs tw:[font-size:var(--font-base)] tw:text-[var(--color-button-toggle-text)] tw:first:ml-0 tw:[&_.button-surface\_\_content]:h-auto tw:[&_.button-surface\_\_content]:justify-center`,
  buttonActive: String.raw`button-bubble--active tw:!bg-[var(--color-button-toggle-bg-active)] tw:!text-[var(--color-button-toggle-text-active)] tw:[box-shadow:unset] tw:hover:cursor-default`,
  buttonInactive: String.raw`tw:hover:!bg-[var(--color-button-toggle-bg-hover)] tw:hover:[&_.button-surface\_\_label]:!text-[var(--color-button-toggle-text-hover)]`,
} as const;

export const RECOMMENDED_CONTENT_CLASS = RECOMMENDED_CONTENT_CLASSES.root;
