export const HOME_TAB_CLASSES = {
  root: String.raw`home-tab tw:mb-[calc(var(--spacing-xxl)*3)] tw:[&_.section\_\_header--actions]:hidden tw:[&_.claim-tile\_\_info]:pb-0 tw:[&_.livestream\_\_channel-link]:mb-app-l tw:[&_.livestream\_\_channel-link]:pb-app-m tw:[&_.livestream\_\_channel-link]:![border-bottom:unset] tw:[&_.claim-preview--tile]:mb-app-l tw:upto-small:[&_.claim-preview--tile]:mb-app-s`,
  actions:
    'channel_sections__actions tw:mb-app-s tw:flex tw:flex-wrap tw:items-center tw:justify-end tw:[&_.button]:mt-app-xs tw:[&_.button]:ml-app-s tw:[&_svg]:cursor-pointer',
  wrapper: String.raw`home-section-wrapper tw:[background:none] tw:[transition:background_0.2s] tw:[&_.order]:hidden tw:[&_.order]:!m-[calc(var(--spacing-s)*2)] tw:[&_.order_.collection-preview\_\_edit-buttons]:h-[100px] tw:[&_.order_.collection-preview\_\_edit-buttons]:w-[unset] tw:[&_.order_.collection-preview\_\_edit-buttons]:[grid-template-columns:1fr_1fr_1fr] tw:[&_.order_.collection-preview\_\_edit-buttons]:rounded-app tw:[&_.order_.collection-preview\_\_edit-buttons]:bg-app-background tw:[&_.order_.collection-preview\_\_edit-group]:!flex tw:[&_.order_.collection-preview\_\_edit-group]:w-[unset] tw:[&_.order_.collection-preview\_\_edit-group:nth-child(1)]:!hidden tw:[&_.order_.collection-preview\_\_edit-group:nth-child(2)_.button-collection-manage:nth-child(1)]:rounded-tl-app tw:[&_.order_.collection-preview\_\_edit-group:nth-child(2)_.button-collection-manage:nth-child(2)]:rounded-bl-app tw:[&_.order_.collection-preview\_\_edit-group_.button-collection-manage:hover]:!bg-app-primary`,
  wrapperEdit: String.raw`home-section-wrapper--edit tw:relative tw:flex tw:w-full tw:[flex-flow:row] tw:rounded-app tw:![background-color:rgba(var(--color-header-button-base),0.3)] tw:mb-app-xs tw:[&_.order]:!inline-block tw:[&_.order]:min-w-[160px] tw:[&_.order]:rounded-app tw:[&_.section]:!m-0 tw:[&_.section]:!mt-app-s tw:[&_.section]:!min-h-[203px] tw:[&_.section]:!w-full tw:[&_.section]:self-end tw:[&_.section]:!rounded-app tw:[&_.section]:!bg-app-header tw:[&_.section]:!px-app-m tw:[&_.section]:!py-app-xs tw:[&_.section]:pointer-events-none tw:[&_.section]:select-none tw:[&_.section]:[-webkit-touch-callout:none] tw:[&_.section]:![transform:scale(0.8)_translateY(-13%)] tw:[&_.section_.show-more]:mr-app-s tw:[&_.section_.claim-preview\_\_wrapper]:bg-[unset] tw:upto-small:[flex-flow:column] tw:upto-small:[&_.order]:!m-app-s tw:upto-small:[&_.order]:!mb-[calc(var(--spacing-s)*-1)] tw:upto-small:[&_.order]:w-[unset] tw:upto-small:[&_.order_.collection-preview\_\_edit-buttons]:h-[50px] tw:upto-small:[&_.order_.collection-preview\_\_edit-buttons]:w-full tw:upto-small:[&_.order_.collection-preview\_\_edit-group]:flex-row tw:upto-small:[&_.section]:!m-app-s tw:upto-small:[&_.section]:!box-border tw:upto-small:[&_.section]:!w-[unset] tw:upto-small:[&_.section]:!max-w-full tw:upto-small:[&_.section]:![transform:scale(1)]`,
  wrapperEditFeatured: 'home-section-wrapper--edit-featured tw:small:max-h-[308px]',
  wrapperEditMultirow: 'tw:small:max-h-[960px] tw:medium:max-h-[758px] tw:large:max-h-[520px]',
  wrapperEditOneRow: 'home-section-wrapper--edit-onerow tw:small:max-h-[360px] tw:large:max-h-[336px]',
  content: 'home-section-content tw:min-w-[84%]',
  section: String.raw`section tw:mr-0 tw:mb-app-m tw:border-b tw:border-b-app-border tw:p-0 tw:pb-app-m tw:[background:none] tw:[transform:scale(1)] tw:[transition:all_0.2s] tw:[&_.channel-section-card]:m-0 tw:[&_.channel-section-card]:bg-[unset] tw:[&_.channel-section-card]:p-0 tw:[&_.channel-section-card_.channel-section-card\_\_header]:hidden tw:[&_.channel-section-card_.channel-section-card\_\_item]:m-0 tw:[&_.channel-section-card_.channel-section-card\_\_item]:mr-app-s tw:[&_.channel-section-card_.channel-section-card\_\_item]:overflow-hidden tw:[&_.channel-section-card_.channel-section-card\_\_item]:rounded-app tw:[&_.channel-section-card_.channel-section-card\_\_item_:is([data-channel-thumbnail-image],.freezeframe-img,.ff-canvas)]:m-app-xs tw:[&_.channel-section-card_.channel-section-card\_\_item_:is([data-channel-thumbnail-image],.freezeframe-img,.ff-canvas)]:size-[4rem] tw:[&_.channel-section-card_.channel-section-card\_\_item_:is([data-channel-thumbnail-image],.freezeframe-img,.ff-canvas)]:[transform:scale(1)] tw:[&_.channel-section-card_.channel-section-card\_\_item_:is([data-channel-thumbnail-image],.freezeframe-img,.ff-canvas)]:[transition:transform_0.2s] tw:[&_.channel-section-card_.channel-section-card\_\_item_.channel-thumbnail--resolving]:bg-[unset] tw:[&_.channel-section-card_.channel-section-card\_\_item_.claim-preview\_\_title]:max-w-full tw:[&_.channel-section-card_.channel-section-card\_\_item_.claim-preview\_\_title]:overflow-hidden tw:[&_.channel-section-card_.channel-section-card\_\_item_.claim-preview\_\_title]:text-ellipsis tw:[&_.channel-section-card_.channel-section-card\_\_item_.claim-preview\_\_title]:text-[rgba(var(--color-text-base),0.9)] tw:[&_.channel-section-card_.channel-section-card\_\_item:last-of-type]:mr-0 tw:[&_.channel-section-card_.channel-section-card\_\_item:hover_:is([data-channel-thumbnail-image],.freezeframe-img,.ff-canvas)]:[transform:scale(1.08)] tw:[&_.channel-section-card_.channel-section-card\_\_item:hover_.claim-preview\_\_title]:text-app-primary`,
  title: 'home-section-title tw:mt-0 tw:mb-app-s tw:inline-block tw:text-app-large',
  showMore: String.raw`show-more tw:absolute tw:right-0 tw:mt-[1px] tw:mb-app-s tw:text-app-primary tw:[&_.icon]:mb-[-3px] tw:hover:cursor-pointer tw:hover:text-app-secondary`,
  headerWrapper:
    'home-section-header-wrapper tw:mx-[10%] tw:flex tw:w-4/5 tw:max-w-[80%] tw:pt-app-s tw:upto-small:mx-app-s tw:upto-small:flex-wrap',
  headerOption: String.raw`home-section-header-option tw:pr-app-s tw:[&_label]:block tw:[&_select]:max-w-[204px] tw:[&_select]:overflow-hidden tw:[&_select]:bg-app-background tw:[&_select:focus-visible]:text-app-text tw:[&_select:focus-visible]:[box-shadow:0_0_0_2px_var(--color-primary)_inset] tw:[&_select:hover]:bg-app-primary tw:[&_select:hover]:text-app-primary-contrast tw:[&_select_option]:bg-[var(--color-header-button)] tw:[&_select_option[disabled]]:cursor-not-allowed tw:[&_select_option[disabled]]:text-[gray] tw:[&_input]:bg-app-background`,
  editBar: String.raw`home-tab-edit tw:fixed tw:bottom-0 tw:z-[99] tw:w-[calc(100%_-_2*var(--spacing-l))] tw:max-w-[var(--page-max-width)] tw:rounded-[var(--border-radius)_var(--border-radius)_0_0] tw:border-2 tw:border-app-border tw:[border-bottom:none] tw:bg-app-header tw:p-app-s tw:[animation-duration:0.2s] tw:[animation-name:moveUp] tw:[backdrop-filter:blur(4px)] tw:[box-shadow:0_1px_4px_1px_var(--color-shadow)] tw:[&_.button]:mr-app-m tw:upto-small:w-[calc(100%_-_2*var(--spacing-xs))]`,
} as const;
