export const CLAIM_PREVIEW_HOVER_ACTIONS_GRID_CLASS = [
  String.raw`tw:absolute tw:inset-x-0 tw:top-0 tw:z-[3] tw:grid tw:justify-between tw:justify-items-end tw:opacity-0`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions]:block tw:[&_.claim-preview\_\_hover-actions]:float-right tw:[&_.claim-preview\_\_hover-actions]:m-app-xxs tw:[&_.claim-preview\_\_hover-actions]:mb-0`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:block tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:m-0 tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:h-[unset] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:px-app-xxs tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:py-app-xxs`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu):hover_.button-surface\_\_label]:inline`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:mr-0 tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:w-auto tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:max-w-[25.59px] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:bg-[var(--color-black)] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:!p-[var(--claim-preview-hover-action-padding,0.3rem)] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)]:[transition:max-width_0.2s]`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_content]:flex-row-reverse tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:mt-0 tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:mr-app-xxs tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:mb-0 tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:ml-[4px] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:hidden tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:text-ellipsis tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:text-app-xsmall tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu)_.button-surface\_\_label]:text-[var(--color-white)]`,
  String.raw`tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu):hover]:w-auto tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu):hover]:min-w-[25.59px] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu):hover]:max-w-[140px] tw:[&_.claim-preview\_\_hover-actions_:is(.file-action-surface--button,.file-action-surface--menu):hover_.icon]:stroke-white`,
  String.raw`tw:[:is(.claim-preview\_\_wrapper,.playlist-preview\_\_wrapper)_&_.icon]:!stroke-white tw:[:is(.claim-preview\_\_wrapper,.playlist-preview\_\_wrapper):hover_.media\_\_thumb_&]:opacity-100`,
  String.raw`tw:[:is(.compact-hover-actions,.file-page\_\_recommended)_&_:is(.file-action-surface--button,.file-action-surface--menu)]:max-w-[21px] tw:[:is(.compact-hover-actions,.file-page\_\_recommended)_&_:is(.file-action-surface--button,.file-action-surface--menu)]:!p-[calc(0.25rem-1px)] tw:[:is(.compact-hover-actions,.file-page\_\_recommended)_&_:is(.file-action-surface--button,.file-action-surface--menu)_.icon]:size-[14px] tw:[:is(.compact-hover-actions,.file-page\_\_recommended)_&_:is(.file-action-surface--button,.file-action-surface--menu):hover]:min-w-[21px] tw:[:is(.compact-hover-actions,.file-page\_\_recommended)_&_.claim-preview\_\_hover-actions+_.claim-preview\_\_hover-actions]:mt-[1px]`,
  String.raw`tw:[.channel-cover~*_&_:is(.file-action-surface--button,.file-action-surface--menu)]:max-w-[21px] tw:[.channel-cover~*_&_:is(.file-action-surface--button,.file-action-surface--menu)]:!p-[calc(0.25rem-1px)] tw:[.channel-cover~*_&_:is(.file-action-surface--button,.file-action-surface--menu)_.icon]:size-[14px] tw:[.channel-cover~*_&_:is(.file-action-surface--button,.file-action-surface--menu):hover]:min-w-[21px] tw:[.channel-cover~*_&_.claim-preview\_\_hover-actions+_.claim-preview\_\_hover-actions]:mt-[1px]`,
  String.raw`tw:[@media(pointer:none)]:[&_.claim-preview\_\_hover-actions]:!hidden tw:[@media(pointer:coarse)]:[&_.claim-preview\_\_hover-actions]:!hidden`,
].join(' ');
