export const NOTIFICATION_CLASSES = {
  menuLink: String.raw`menu__link--notification tw:relative tw:z-[2] tw:flex tw:w-full tw:items-start tw:hover:cursor-pointer tw:[&_.icon\_\_wrapper]:size-[2.5rem] tw:[&_.icon\_\_wrapper]:text-app-text`,
  menuLinkNoLink: String.raw`menu__link--notification-nolink tw:relative tw:z-[2] tw:flex tw:w-full tw:cursor-default tw:items-start tw:[&_.icon\_\_wrapper]:size-[2.5rem] tw:[&_.icon\_\_wrapper]:text-app-text`,
  menuLinkWithOverlay: String.raw`menu__link--notification--with-overlay tw:pointer-events-none tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore])]:pointer-events-auto tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore])]:relative tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore])]:z-[2]`,
  linkOverlay: 'notification__link-overlay tw:pointer-events-auto tw:absolute tw:inset-0 tw:z-[1]',
  wrapper: String.raw`notification__wrapper tw:relative tw:flex tw:w-full tw:flex-col tw:justify-between tw:px-0 tw:py-app-m tw:[&_.date_time]:text-app-small tw:[&_.icon\_\_wrapper]:bg-app-background tw:[&_.comment\_\_creator-like]:absolute tw:[&_.comment\_\_creator-like]:top-[0.4rem] tw:[&_.comment\_\_creator-like]:left-[0.4rem] tw:[&_.comment\_\_creator-like]:z-[3] tw:[&_.comment\_\_creator-like]:ml-[3px] tw:[&_.comment\_\_creator-like]:size-[0.8rem] tw:upto-small:p-app-s`,
  pageWrapper: String.raw`tw:mb-app-xxs tw:rounded-app tw:bg-[rgba(var(--color-header-button-base),0.4)] tw:first:[border-top:none] tw:hover:cursor-pointer tw:hover:bg-[rgba(var(--color-header-button-base),0.9)] tw:hover:[&_.menu\_\_button]:opacity-100 tw:hover:[&_:is(.notificationText\_\_wrapper,.notification\_\_text)]:text-app-primary tw:[&_.notification\_\_menu]:mr-app-s tw:[&_.notification\_\_menu_.icon]:stroke-[var(--color-text)] tw:[&_.notification\_\_menu_.menu\_\_button_.icon]:[transition:transform_0.2s] tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button]:rounded-[50%] tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button]:bg-[rgba(var(--color-header-button-base),0.9)] tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button]:opacity-100 tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button]:[outline:2px_solid_var(--color-header-background)] tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button_.icon]:[stroke:var(--color-primary)] tw:[&_.notification\_\_menu_[aria-expanded='true'].menu\_\_button_.icon]:[transform:rotate(-90deg)] tw:[&_.comment-create]:[border-top:1px_solid_var(--color-border)] tw:[&_.comment-create]:pt-app-s tw:[&_.comment-create_.comment-create\_\_label]:text-app-text tw:[&_.comment-create_:is(textarea,select)]:bg-app-background tw:[&_.comment-create_.button:not(.file-action-surface)]:bg-app-background tw:[&_.comment-create_.button]:rounded-app tw:[&_.comment-create_.comment\_\_char-count-mde]:pr-0 tw:[&_.comment-create_.file-action-surface_.button-surface\_\_content_.icon]:bg-[var(--color-header-button)] tw:[&_:is(.comment-create,.comment\_\_content)]:m-app-m tw:[&_:is(.comment-create,.comment\_\_content)]:mb-0 tw:[&_.notification\_\_title]:my-[4px] tw:[&_:is(.notificationText\_\_wrapper,.notification\_\_text)]:text-app-body tw:upto-small:[&_.notification\_\_menu]:mr-[calc(var(--spacing-xs)*-1)] tw:upto-small:[&_.notification\_\_menu_.menu\_\_button]:opacity-100 tw:upto-small:[&_.MuiAutocomplete-root]:bg-app-background`,
  unread: String.raw`notification__wrapper--unread tw:justify-between tw:[box-shadow:2px_0_0_0_rgba(var(--color-primary-dynamic),0.7)_inset] tw:hover:[box-shadow:2px_0_0_0_rgba(var(--color-primary-dynamic),1)_inset] tw:upto-small:p-app-s`,
  icon: String.raw`notification__icon tw:mt-app-xxs tw:flex tw:items-start tw:[&_.icon\_\_wrapper]:mr-app-m tw:[&_.icon\_\_wrapper.icon\_\_wrapper]:size-[1rem] tw:[&_.icon\_\_wrapper]:rounded-app tw:[&_.icon\_\_wrapper]:p-[1.2rem] tw:small:ml-app-m tw:small:items-center tw:small:[&_.icon\_\_wrapper]:p-[1.5rem]`,
  channelThumbnail: String.raw`tw:!size-[3rem] tw:[&_:is(.ff-canvas,.freezeframe-img)]:size-full tw:[&_:is(.ff-canvas,.freezeframe-img)]:rounded-[50%] tw:upto-small:!size-[2rem]`,
  contentWrapper:
    'notificationContent__wrapper tw:flex tw:flex-1 tw:flex-col tw:justify-between tw:small:flex-row tw:small:items-center',
  content:
    'notification__content tw:flex tw:max-w-[60rem] tw:flex-1 tw:flex-col tw:justify-between tw:small:flex-row tw:small:items-center',
  thumbnail: String.raw`notificationContent__thumbnail tw:relative tw:mt-app-s tw:ml-auto tw:h-auto tw:w-full tw:before:float-left tw:before:pt-[var(--aspect-ratio-standard)] tw:before:content-[''] tw:after:block tw:after:clear-both tw:after:content-[''] tw:small:mt-0 tw:small:ml-app-m tw:small:min-w-0 tw:small:w-[calc(4rem*16/9)] tw:small:max-w-[calc(4rem*16/9)]`,
  textWrapper: String.raw`notificationText__wrapper tw:max-w-[calc(60rem-(4rem*16/9)-var(--spacing-m))] tw:overflow-hidden tw:text-app-small tw:text-app-text tw:[display:-webkit-box] tw:[-webkit-box-orient:vertical] tw:[-webkit-line-clamp:1] tw:[&_.sticker\_\_comment]:size-[4.5rem]`,
  title: String.raw`notification__title tw:relative tw:shrink tw:overflow-hidden tw:text-app-xsmall tw:text-app-text-subtitle tw:[display:-webkit-box] tw:[-webkit-box-orient:vertical] tw:[-webkit-line-clamp:1] tw:[&_.channel-name]:text-[unset] tw:upto-small:mb-0`,
  claimTitle: 'notification__claim-title tw:[font-weight:var(--font-weight-bold)]',
  text: String.raw`notification__text tw:shrink tw:overflow-hidden tw:text-app-small tw:text-app-text tw:[display:-webkit-box] tw:[-webkit-box-orient:vertical] tw:[-webkit-line-clamp:1]`,
  replies: String.raw`notification__text--replies tw:italic tw:[&_blockquote]:break-all tw:[&_blockquote]:[border-left:2px_solid] tw:[&_blockquote]:pl-app-xs tw:[&_blockquote]:!text-app-text`,
  time: 'notification__time tw:mt-app-s tw:shrink-0 tw:text-app-small tw:text-app-text tw:small:mt-0 tw:small:ml-app-s',
  reactions: String.raw`notification__reactions tw:m-app-m tw:mb-0 tw:flex tw:[&>*:not(:last-of-type)]:mr-app-m tw:[&_.button-surface\_\_label]:ml-app-xs tw:small:ml-[5rem] tw:upto-small:ml-[3rem]`,
  extra:
    'notification__extra tw:mr-app-m tw:flex tw:h-full tw:self-start tw:small:mt-0 tw:small:ml-app-s tw:small:flex-row',
  markSeen:
    'notification__markSeen tw:mt-app-s tw:ml-app-s tw:size-[12px] tw:rounded-[50%] tw:bg-app-primary tw:small:mt-[4px] tw:upto-small:mt-[15px] tw:upto-small:mr-app-xxs tw:upto-small:ml-0',
  menu: String.raw`notification__menu tw:mr-app-m tw:[&_.icon]:[stroke:var(--color-text-help)]`,
} as const;
