const CREATOR_TIER_EDITOR_FORM_FIELDS = String.raw`tw:p-app-m tw:[&_:is(label,.confirm\_\_label)]:text-app-body tw:[&_:is(input,textarea)]:[border:2px_solid_var(--color-border)] tw:[&_:is(input,textarea)]:![overflow:auto] tw:[&_textarea]:min-h-[8rem] tw:[&_textarea]:resize-y tw:[&_textarea]:whitespace-pre-wrap tw:[&_textarea]:rounded-app tw:[&_textarea]:p-app-s tw:[&_:is(fieldset-section,.fieldset-section)]:mt-app-m tw:[&_:is(fieldset-section,.fieldset-section):first-of-type]:mt-0 tw:[&_.checkbox]:mt-app-xs tw:[&_.checkbox_:is(label,.confirm\_\_label)]:![font-size:var(--font-base)] tw:[&_.checkbox_:is(label,.confirm\_\_label)]:opacity-80`;

const CREATOR_TIER_EDITOR_FORM_ACTIONS = String.raw`tw:[&_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)]:mt-app-m tw:[&_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)]:![margin-bottom:calc(var(--spacing-m)*-1)] tw:[&_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_.button-surface--primary]:[--button-surface-primary-bg:var(--color-primary)] tw:upto-small:[&_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_.button-surface--primary]:![margin-right:var(--spacing-s)]`;

const CREATOR_TIER_EDITOR_FORM_HELP = String.raw`tw:[&_:is(.help,.wunderbar\_\_suggestion-name,.help--warning,.help--notice,.help--inline,.help--card-actions,.help--dt,.help--error,.block-modal--active-channel-label,.footer\_\_link,.form-field\_\_help,.media\_\_details)]:mt-[calc(var(--spacing-s)*-1)] tw:[&_:is(.help,.wunderbar\_\_suggestion-name,.help--warning,.help--notice,.help--inline,.help--card-actions,.help--dt,.help--error,.block-modal--active-channel-label,.footer\_\_link,.form-field\_\_help,.media\_\_details)]:mb-app-s`;

const CREATOR_TIER_EDITOR_FORM_AUTOCOMPLETE = String.raw`tw:[&_.MuiAutocomplete-option_.textarea-suggestion\_\_label_.textarea-suggestion\_\_value]:mt-[calc(var(--spacing-s)*-1)] tw:[&_.MuiAutocomplete-option_.textarea-suggestion\_\_label_.textarea-suggestion\_\_value]:mb-app-s tw:[.MuiAutocomplete-option_.textarea-suggestion\_\_label_&_.textarea-suggestion\_\_value]:mb-app-s`;

export const CREATOR_TIER_EDITOR_CLASSES = {
  form: `${CREATOR_TIER_EDITOR_FORM_FIELDS} ${CREATOR_TIER_EDITOR_FORM_ACTIONS} ${CREATOR_TIER_EDITOR_FORM_HELP} ${CREATOR_TIER_EDITOR_FORM_AUTOCOMPLETE}`,
} as const;
