#!/usr/bin/env python3
"""Regenerate the real LBRY channel-key fixtures used by the wallet-migration
tests (src/core/include/lbry_test_keys.hrl).

Each key is generated by coincurve (the library LBRY uses), PEM-exported exactly
as Account.add_channel_private_key stores it, and packed into a genuine
wallet-sync blob with the LBRY SDK's own crypto -- so the fixtures exercise the
real format end to end, and the empty-password blob proves the bulk-migration
cohort is server-decryptable while the password blob proves the rest must be
lazy.

    python3 -m venv /tmp/.venv
    /tmp/.venv/bin/pip install coincurve cryptography asn1crypto
    PYTHONPATH=/path/to/lbry-sdk /tmp/.venv/bin/python3 scripts/gen-lbry-channel-keys.py
"""
import json
import sys

from lbry.crypto.crypt import better_aes_encrypt, better_aes_decrypt
from coincurve import PrivateKey as cPrivateKey


def main(count=3):
    keys = [cPrivateKey() for _ in range(count)]
    certificates = {f"fakeaddr{i}": k.to_pem().decode() for i, k in enumerate(keys)}
    wallet = {
        "version": 1, "name": "testwallet", "preferences": {},
        "accounts": [{
            "ledger": "lbc_mainnet", "name": "Account #1",
            "seed": "test seed words here", "private_key": "tprvFAKExprv",
            "certificates": certificates,
        }],
    }
    plaintext = json.dumps(wallet).encode()
    blob_empty = better_aes_encrypt("", plaintext)
    blob_pass = better_aes_encrypt("hunter2", plaintext)

    # Prove the crux: empty-password blobs decrypt with no secret (bulk cohort);
    # password blobs need the password (lazy cohort).
    assert json.loads(better_aes_decrypt("", blob_empty)) == wallet
    try:
        better_aes_decrypt("", blob_pass)
        raise SystemExit("password blob unexpectedly opened with empty password")
    except Exception:
        pass

    for i, k in enumerate(keys):
        print(f"key {i}: scalar {k.secret.hex()}")
        print(k.to_pem().decode())


if __name__ == "__main__":
    main(int(sys.argv[1]) if len(sys.argv) > 1 else 3)
