export const MEDIA_INFO_TEXT_CLASS = String.raw`media__info-text tw:[word-break:break-word] tw:not-last-of-type:mb-app-m tw:[.channelPage-wrapper_&]:text-app-base! tw:[.channelPage-wrapper_&]:opacity-80 tw:[.channelPage-wrapper_&:first-of-type]:opacity-100`;

export const MEDIA_INFO_TEXT_CONSTRAINED_CLASS = 'media__info-text--constrained tw:max-w-[50rem] tw:text-app-small';

export const MEDIA_URI_CLASS = String.raw`media__uri tw:absolute tw:flex tw:[transform:translateY(-130%)] tw:text-app-xsmall tw:font-normal tw:text-app-text-subtitle tw:upto-small:static tw:upto-small:mb-app-xs tw:upto-small:max-w-full tw:upto-small:transform-none tw:upto-small:whitespace-nowrap tw:active-fullscreen-side-panel:static tw:active-fullscreen-side-panel:mb-app-xs tw:active-fullscreen-side-panel:max-w-full tw:active-fullscreen-side-panel:transform-none tw:active-fullscreen-side-panel:whitespace-nowrap`;

export const MEDIA_ACTIONS_CLASS = String.raw`media__actions tw:relative tw:mt-0 tw:flex tw:[&>*:not(:last-child)]:mr-app-m tw:[&_.button:hover]:text-[var(--color-link)] tw:upto-small:m-0 tw:upto-small:flex-wrap tw:upto-small:!justify-around tw:upto-small:p-0 tw:upto-small:[&>*]:mr-app-s tw:upto-small:[&>*]:mb-app-s tw:upto-small:[&_.button]:min-w-0 tw:upto-small:[&_.button]:grow tw:upto-small:[&_.button]:basis-0 tw:active-fullscreen-side-panel:m-0 tw:active-fullscreen-side-panel:flex-wrap tw:active-fullscreen-side-panel:!justify-around tw:active-fullscreen-side-panel:p-0 tw:active-fullscreen-side-panel:[&>*]:mr-app-s tw:active-fullscreen-side-panel:[&>*]:mb-app-s tw:active-fullscreen-side-panel:[&_.button]:min-w-0 tw:active-fullscreen-side-panel:[&_.button]:grow tw:active-fullscreen-side-panel:[&_.button]:basis-0`;

export const MEDIA_ACTIONS_STRETCH_CLASS = String.raw`stretch tw:upto-small:mt-app-xxxs tw:upto-small:[&_.button]:mr-app-xxs tw:upto-small:[&_.button]:flex-auto tw:upto-small:[&_.button_.button-surface\_\_content]:justify-center tw:upto-small:[&_.section]:mr-[unset] tw:upto-small:[&_.section]:ml-app-xxs tw:upto-small:[&_.section_.button]:mr-0 tw:active-fullscreen-side-panel:mt-app-xxxs tw:active-fullscreen-side-panel:[&_.button]:mr-app-xxs tw:active-fullscreen-side-panel:[&_.button]:flex-auto tw:active-fullscreen-side-panel:[&_.button_.button-surface\_\_content]:justify-center tw:active-fullscreen-side-panel:[&_.section]:mr-[unset] tw:active-fullscreen-side-panel:[&_.section]:ml-app-xxs tw:active-fullscreen-side-panel:[&_.section_.button]:mr-0`;
