const SECTION_ACTIONS_LINK_CLASS = String.raw`tw:[&_:is(.button-surface--primary,.button-surface--secondary)~:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:h-[var(--button-height)] tw:[&_:is(.button-surface--primary,.button-surface--secondary)~:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:px-app-m tw:[&_:is(.button-surface--primary,.button-surface--secondary)~:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:py-app-s tw:upto-small:[&_:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:!p-0`;

const SECTION_ACTIONS_LAYOUT_CLASS = `${String.raw`tw:relative tw:flex tw:items-center tw:gap-app-xs tw:upto-medium:flex-wrap tw:[&~.section]:mt-app-m tw:[&_[aria-expanded='true'].file-action-surface--button:last-of-type]:bg-[var(--color-header-background)] tw:[&_[aria-expanded='true'].file-action-surface--menu:last-of-type]:bg-[var(--color-header-background)] tw:[&_.markdown-preview_:is(.button-surface--primary,.button-surface--secondary)~a]:h-[var(--button-height)] tw:[&_.markdown-preview_:is(.button-surface--primary,.button-surface--secondary)~a]:px-app-m tw:[&_.markdown-preview_:is(.button-surface--primary,.button-surface--secondary)~a]:py-app-s tw:[.markdown-preview_&_:is(.button-surface--primary,.button-surface--secondary)~a]:h-[var(--button-height)] tw:[.markdown-preview_&_:is(.button-surface--primary,.button-surface--secondary)~a]:px-app-m tw:[.markdown-preview_&_:is(.button-surface--primary,.button-surface--secondary)~a]:py-app-s tw:upto-small:[&_.markdown-preview_a]:!p-0 tw:upto-small:[.markdown-preview_&_a]:!p-0`} ${SECTION_ACTIONS_LINK_CLASS}`;

const SECTION_ACTIONS_SPACED_CLASS = 'tw:mt-app-s tw:first:mt-0 tw:only:mt-0 tw:upto-small:mt-app-xxs';

export const SECTION_CLASSES = {
  actions: `section__actions ${SECTION_ACTIONS_LAYOUT_CLASS} ${SECTION_ACTIONS_SPACED_CLASS}`,
  actionsBetween: `${String.raw`section__actions--between ${SECTION_ACTIONS_LAYOUT_CLASS}`} tw:mt-0 tw:ml-auto tw:justify-between tw:[border-top:unset] tw:py-app-s tw:upto-small:justify-start`,
  actionsCentered: `section__actions--centered ${SECTION_ACTIONS_LAYOUT_CLASS} ${SECTION_ACTIONS_SPACED_CLASS} tw:justify-center tw:upto-small:justify-start`,
  actionsInline: 'section__actions--inline',
  actionsNoMargin: String.raw`section__actions--no-margin ${SECTION_ACTIONS_LAYOUT_CLASS} tw:mt-0 tw:upto-small:w-full tw:upto-small:[display:unset] tw:upto-small:text-right tw:upto-small:[&_:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:mb-0 tw:upto-small:[&_.markdown-preview_a]:mb-0 tw:upto-small:[.markdown-preview_&_a]:mb-0 tw:upto-small:[&_.wunderbar--inline]:w-full tw:upto-small:[&_.wunderbar--inline]:[flex:unset] tw:upto-small:[&_.wunderbar--inline_fieldset-section]:w-full tw:upto-small:[&_.wunderbar--inline_.fieldset-section]:w-full tw:upto-small:[&_.wunderbar--inline_fieldset-section_.wunderbar\_\_input--inline]:w-full tw:upto-small:[&_.wunderbar--inline_.fieldset-section_.wunderbar\_\_input--inline]:w-full tw:upto-small:[&_.wunderbar--inline_fieldset-section_.wunderbar\_\_input--inline:focus-visible]:![outline:unset] tw:upto-small:[&_.wunderbar--inline_.fieldset-section_.wunderbar\_\_input--inline:focus-visible]:![outline:unset] tw:upto-small:[&_.wunderbar--inline_fieldset-section_.wunderbar\_\_input--inline:focus-visible]:![box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset] tw:upto-small:[&_.wunderbar--inline_.fieldset-section_.wunderbar\_\_input--inline:focus-visible]:![box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset] tw:upto-small:[&_.button-surface--secondary]:w-full`,
  body: 'section__body tw:mt-app-m',
  checkbox:
    'section__checkbox tw:mt-app-l tw:flex tw:items-center tw:[&_fieldset-section]:mt-0 tw:[&_fieldset-section]:w-[6em] tw:[&_.fieldset-section]:mt-0 tw:[&_.fieldset-section]:w-[6em] tw:[&_.checkbox]:mr-[10px]',
  divider: String.raw`section__divider tw:relative tw:flex tw:flex-col tw:items-center tw:[&_hr]:my-app-xl tw:[&_p]:absolute tw:[&_p]:top-[calc(var(--spacing-xl)/2+10px)] tw:[&_p]:h-app-l tw:[&_p]:rounded-app tw:[&_p]:bg-app-header tw:[&_p]:px-app-s tw:[&_p]:py-0 tw:[&_p]:text-center tw:[&_p]:text-app-large tw:[&_p]:[color:var(--color-subtitle)] tw:[&_p]:[font-weight:var(--font-weight-base)]`,
  headerActions: String.raw`section__header--actions tw:mt-app-m tw:mb-app-l tw:flex tw:flex-wrap tw:items-start tw:justify-between tw:[&_.button-surface--secondary]:bg-[var(--color-secondary)] tw:[&_.button-surface--secondary_.button-surface\_\_label]:text-[var(--color-menu-icon-active)] tw:[&_.button-surface--secondary_.icon]:stroke-[var(--color-menu-icon-active)] tw:[&_.section\_\_actions--no-margin_:is(.help,.wunderbar\_\_suggestion-name,.help--warning,.help--notice,.help--inline,.help--card-actions,.help--dt,.help--error,.block-modal--active-channel-label,.footer\_\_link,.form-field\_\_help,.media\_\_details)]:text-app-text tw:[&_.section\_\_actions--no-margin_.MuiAutocomplete-option_.textarea-suggestion\_\_label_.textarea-suggestion\_\_value]:text-app-text tw:[.MuiAutocomplete-option_.textarea-suggestion\_\_label_&_.section\_\_actions--no-margin_.textarea-suggestion\_\_value]:text-app-text tw:[&_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)]:flex-1 tw:upto-small:mt-app-s tw:upto-small:mb-app-s tw:upto-small:w-full tw:upto-small:pt-0`,
  padded: 'section--padded tw:p-app-m',
  subtitle: 'section__subtitle tw:text-app-body tw:text-app-text-subtitle',
  title: 'section__title tw:text-left tw:text-app-large tw:[font-weight:var(--font-weight-light)]',
  titleMarginBottom: 'section__title--margin-bottom tw:mt-0 tw:mb-app-m',
  titleSmall: String.raw`section__title--small tw:text-left tw:text-app-body tw:[font-weight:var(--font-weight-light)] tw:[&_.button]:ml-app-s tw:not-first-of-type:mt-app-m`,
  verticalCompact:
    'section--vertical-compact tw:[&_:is(fieldset-section,.fieldset-section,fieldset-section.radio,div.checkbox,div.section)]:mt-app-m tw:[&_:is(fieldset-section,.fieldset-section,fieldset-section.radio,div.checkbox,div.section)]:mb-app-s',
} as const;
