export const SETTINGS_ROW_CLASSES = {
  root: String.raw`settings-row tw:border-b tw:border-b-app-border tw:p-app-s tw:first:[border-top:none] tw:only:[border-top:none] tw:first-of-type:p-0 tw:[.card\_\_body.card\_\_body--list_&:first-of-type]:!p-app-s tw:[.card\_\_body.card\_\_body--list_&:last-of-type]:![border-bottom:unset] tw:[&_.help--warning]:my-0 tw:[&_.help--notice]:my-0 tw:[&_.fieldset-group--smushed_label]:ml-0 tw:[&_.fieldset-group--smushed_.confirm\_\_label]:ml-0 tw:[&_.fieldset-group--smushed_fieldset-section:last-of-type]:ml-[2px] tw:[&_.fieldset-group--smushed_.fieldset-section:last-of-type]:ml-[2px] tw:upto-small:[flex-flow:row] tw:upto-small:p-app-xs`,
  disabled: 'tw:opacity-40',
  highlighted: 'tw:bg-[var(--color-fire-outside)]',
  membersOnly:
    'settings-row__members-only tw:ml-app-m tw:rounded-[5px] tw:border tw:border-solid tw:border-app-secondary tw:pt-[1px] tw:pr-app-xxs tw:pb-0 tw:pl-app-xxs tw:align-middle tw:text-app-xxsmall tw:text-app-secondary',
  subtitle: String.raw`settings-row__subtitle tw:mt-[calc(var(--spacing-xxs)/2)] tw:text-app-small tw:text-app-text-subtitle tw:[.section\_\_actions--between_&]:text-[rgba(var(--color-text-base),0.6)] tw:[.modal--send-tip_&]:mt-app-xs tw:[section.preorder-content-modal_&]:max-w-[421px] tw:[section.preorder-content-modal_&]:text-center tw:[section.preorder-content-modal-loading_&]:mt-[27px] tw:[section.preorder-content-modal-loading_&]:text-center`,
  title: String.raw`settings-row__title tw:min-w-full tw:self-start tw:[.section\_\_actions--between_&]:text-[rgba(var(--color-text-base),0.9)] tw:[.section\_\_actions--between:hover:not(.opacity-30)_&]:text-[rgba(var(--color-text-base),1)] tw:small:min-w-[60%] tw:small:max-w-[60%] tw:upto-small:[.settings-row_&]:min-w-[unset] tw:upto-small:[.settings-row_&]:max-w-[60%]`,
  value: String.raw`settings-row__value tw:w-full tw:[.section\_\_actions--between_&]:[align-self:start] tw:[&_fieldset-section.radio]:mt-0 tw:[&_.radio.fieldset-section]:mt-0 tw:[&_fieldset-group]:mt-app-m tw:[&_.fieldset-group]:mt-app-m tw:[&_.tags\_\_input-wrapper_.tag\_\_input]:h-[unset] tw:[&_.tags\_\_input-wrapper_.tag\_\_input]:max-w-[unset] tw:[&_.form-field--price-amount]:max-w-[unset] tw:medium:w-[40%] tw:medium:[&_.button:only-child]:float-right tw:medium:[&_.checkbox:only-child]:float-right tw:medium:[&_.section\_\_actions:only-child]:float-right tw:medium:[&_.section\_\_actions--centered:only-child]:float-right tw:medium:[&_.section\_\_actions--between:only-child]:float-right tw:medium:[&_.section\_\_actions--no-margin:only-child]:float-right tw:medium:[&_input]:self-end tw:upto-small:ml-auto tw:upto-small:w-[unset] tw:upto-small:[justify-content:end]`,
  valueMultirow:
    'settings-row__value--multirow tw:medium:!w-[80%] tw:medium:[&_input]:self-start tw:upto-small:mt-app-m',
  valueNonClickable: 'tw:pointer-events-none',
  valueVerticalSeparator: 'settings-row__vertical-separator tw:medium:border-l tw:medium:border-l-app-border',
} as const;
