const HIDDEN_SHORTS_CONTROL = String.raw`tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!pointer-events-none tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!opacity-0 tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!delay-0 tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!duration-50`;
const DISABLED_MOBILE_CONTROL = String.raw`tw:[.media-controls[data-mobile-hidden]_&]:!pointer-events-none tw:[.media-controls[data-mobile-hidden]_&_*]:!pointer-events-none`;

export const MOBILE_CONTROL_LAYOUT_CLASSES = {
  root: String.raw`odysee-mobile-controls tw:pointer-events-none tw:absolute tw:inset-0 tw:z-10 tw:block tw:![background:none] tw:![backdrop-filter:none] tw:!rounded-none tw:![box-shadow:none] tw:!p-0 tw:!gap-0 tw:!text-[oklch(100%_0_0deg)] tw:after:!hidden tw:[&:not([data-visible])]:!scale-100 tw:[&:not([data-visible])]:!filter-none tw:[&[data-mobile-hidden]]:!pointer-events-none tw:[&[data-mobile-hidden]]:!opacity-0 tw:[&[data-mobile-hidden]]:!delay-0 tw:[&[data-mobile-hidden]]:!duration-50 tw:[&[data-mobile-hidden]_*]:!pointer-events-none tw:[.shorts\_\_viewer_&[data-mobile-hidden]]:!opacity-100`,
  top: String.raw`odysee-mobile-controls__top tw:pointer-events-auto tw:absolute tw:top-[var(--spacing-xs)] tw:right-[var(--spacing-xs)] tw:flex tw:items-center tw:gap-[0.075rem] tw:rounded-[9999px] tw:p-[0.175rem] tw:upto-shorts:[.shorts\_\_viewer_&]:top-[60px] ${DISABLED_MOBILE_CONTROL} ${HIDDEN_SHORTS_CONTROL} tw:[.player-fullscreen-target:fullscreen:has(.video-fullscreen\_\_actions--shorts)_&]:hidden tw:[html.ios-fullscreen_.player-fullscreen-target:has(.video-fullscreen\_\_actions--shorts)_&]:hidden`,
  bottom: String.raw`tw:pointer-events-auto tw:absolute tw:right-[var(--spacing-xs)] tw:bottom-[18px] tw:left-[var(--spacing-xs)] tw:flex tw:items-center tw:justify-between ${DISABLED_MOBILE_CONTROL} tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!opacity-100`,
  capsule: 'tw:flex tw:items-center tw:rounded-[9999px] tw:p-[0.175rem]',
  time: String.raw`${DISABLED_MOBILE_CONTROL} ${HIDDEN_SHORTS_CONTROL} tw:[&_.media-time]:h-[34px] tw:[&_.media-time]:cursor-pointer tw:[&_.media-time]:gap-[3px] tw:[&_.media-time]:rounded-[9999px] tw:[&_.media-time]:px-2 tw:[&_.media-time]:py-0 tw:[&_.media-time]:[container:none] tw:[&_.media-time]:[flex:0_0_auto] tw:[&_.media-time_.media-time\_\_value:first-child]:!block`,
  fullscreen: String.raw`${DISABLED_MOBILE_CONTROL} tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden][data-mobile-hidden]_&]:!pointer-events-auto tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&]:!opacity-100 tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden][data-mobile-hidden]_&_*]:!pointer-events-auto tw:[.shorts\_\_viewer_.media-controls[data-mobile-hidden]_&_*]:!opacity-100`,
} as const;
