const FLOATING_PROGRESS = String.raw`tw:upto-small:[[data-floating-player]_&]:!top-auto tw:upto-small:[[data-floating-player]_&]:!right-0 tw:upto-small:[[data-floating-player]_&]:!bottom-0 tw:upto-small:[[data-floating-player]_&]:!left-0 tw:upto-small:[[data-floating-player]_&]:![inset-inline:0] tw:upto-small:[[data-floating-player]_&]:!z-[1] tw:upto-small:[[data-floating-player]_&]:!h-[2px] tw:upto-small:[[data-floating-player]_&]:!pointer-events-none tw:upto-small:[[data-floating-player]_&]:!opacity-100 tw:upto-small:[[data-floating-player]_&]:![transition:none]`;
const FLOATING_SLIDER_RADIUS = String.raw`tw:upto-small:[[data-floating-player]_&]:!rounded-none`;

export const PROGRESS_CONTROL_CLASSES = {
  root: String.raw`odysee-progress-bar tw:absolute tw:z-[11] tw:bottom-[calc(var(--spacing-xs)+var(--media-controls-bar-height,40px))] tw:[inset-inline:var(--spacing-xs)] tw:[transition:opacity_0.1s_ease] tw:[.odysee-skin:not(.odysee-skin--casting):has(.media-controls:not(.odysee-mobile-controls):not([data-visible])):not(:has(.media-button--settings-open))_&]:pointer-events-none tw:[.odysee-skin:not(.odysee-skin--casting):has(.media-controls:not(.odysee-mobile-controls):not([data-visible])):not(:has(.media-button--settings-open))_&]:opacity-0 tw:[.odysee-skin:not(.odysee-skin--casting):has(.media-controls:not(.odysee-mobile-controls):not([data-visible])):not(:has(.media-button--settings-open))_&]:delay-500 tw:[@media(pointer:fine)]:[.odysee-skin:has(.media-controls.odysee-mobile-controls:not([data-visible])):not(:has(.media-button--settings-open))_&]:pointer-events-none tw:[@media(pointer:fine)]:[.odysee-skin:has(.media-controls.odysee-mobile-controls:not([data-visible])):not(:has(.media-button--settings-open))_&]:opacity-0 tw:[@media(pointer:fine)]:[.odysee-skin:has(.media-controls.odysee-mobile-controls:not([data-visible])):not(:has(.media-button--settings-open))_&]:delay-500 tw:[.odysee-skin:has(.media-controls[data-mobile-hidden])_&]:pointer-events-none tw:[.odysee-skin:has(.media-controls[data-mobile-hidden])_&]:opacity-0 tw:[.odysee-skin:has(.media-controls[data-mobile-hidden])_&]:delay-0 tw:[.odysee-skin--casting_&]:!pointer-events-auto tw:[.odysee-skin--casting_&]:!opacity-100 tw:[.odysee-skin--casting_&]:!delay-0 tw:[[data-floating-player]:hover_&]:!pointer-events-auto tw:[[data-floating-player]:hover_&]:!opacity-100 tw:[[data-floating-player]:hover_&]:!delay-0 tw:[[data-floating-player]:has([data-paused])_&]:!pointer-events-auto tw:[[data-floating-player]:has([data-paused])_&]:!opacity-100 tw:[[data-floating-player]:has([data-paused])_&]:!delay-0 tw:[.odysee-skin:has(.odysee-mobile-controls)_&]:bottom-0 tw:[.odysee-skin:has(.odysee-mobile-controls)_&]:[inset-inline:var(--spacing-xs)] ${FLOATING_PROGRESS}`,
  slider: String.raw`odysee-time-slider tw:!cursor-pointer tw:upto-small:[[data-floating-player]_&]:!h-[2px] tw:upto-small:[[data-floating-player]_&]:!min-h-0 tw:upto-small:[[data-floating-player]_&]:!cursor-default tw:upto-small:[[data-floating-player]_&]:!p-0`,
  track: String.raw`tw:!h-[0.3em] tw:rounded-[4px] tw:!bg-[rgba(80,80,80,0.7)] tw:[transition:transform_0.15s_ease] tw:[.odysee-progress-bar:hover_&]:[transform:scaleY(1.6)] tw:[.odysee-progress-bar:hover_&]:after:pointer-events-none tw:[.odysee-progress-bar:hover_&]:after:absolute tw:[.odysee-progress-bar:hover_&]:after:top-0 tw:[.odysee-progress-bar:hover_&]:after:bottom-0 tw:[.odysee-progress-bar:hover_&]:after:left-0 tw:[.odysee-progress-bar:hover_&]:after:w-[var(--media-slider-pointer)] tw:[.odysee-progress-bar:hover_&]:after:rounded-[4px] tw:[.odysee-progress-bar:hover_&]:after:[background:rgba(255,255,255,0.35)] tw:[.odysee-progress-bar:hover_&]:after:content-[''] ${FLOATING_SLIDER_RADIUS}`,
  fill: String.raw`tw:!z-[2] tw:!h-full tw:rounded-[4px] tw:!bg-transparent tw:![background-image:var(--color-odysee-gradient)] ${FLOATING_SLIDER_RADIUS}`,
  buffer: String.raw`tw:!z-[1] tw:!h-full tw:rounded-[4px] tw:!bg-[rgb(155,155,155)] ${FLOATING_SLIDER_RADIUS}`,
  thumb:
    'tw:!size-[0.85em] tw:!rounded-[50%] tw:!bg-[#f77937] tw:![box-shadow:none] tw:![outline:none] tw:[.odysee-progress-bar:hover_&]:!opacity-100',
} as const;
