export const COLLECTION_HEADER_CLASSES = {
  wrapper: 'collection-header__wrapper tw:relative tw:w-full',
  backgroundWrapper:
    'background__wrapper tw:absolute tw:size-full tw:overflow-hidden tw:rounded-app tw:bg-[rgba(var(--color-header-button-base),0.4)]',
  background:
    'background tw:size-full tw:bg-fixed tw:bg-cover tw:bg-center tw:bg-no-repeat tw:opacity-30 tw:![filter:blur(12px)]',
  pending: String.raw`pending-change tw:h-[var(--height-button)] tw:rounded-app tw:bg-[rgba(244,44,44,0.9)] tw:[&_.spinner]:h-[20px] tw:upto-small:mt-app-xxs tw:upto-small:w-[31px] tw:upto-small:[&_.spinner]:!items-[unset]`,
  content:
    'collection-header__content tw:relative tw:top-0 tw:left-0 tw:flex tw:w-full tw:flex-col tw:p-app-m tw:upto-small:p-app-xxs',
  contentTop: 'collection-header__content-top tw:flex',
  title: String.raw`collection-header__title tw:flex tw:flex-col tw:text-app-large tw:font-[var(--font-weight-bold)] tw:[&_.claim-preview--channel]:mb-app-s tw:[&_.claim-preview--channel_.button-surface\_\_content]:[align-items:start] tw:[&_.claim-preview--channel_.channel-thumbnail]:mr-app-s tw:[&_.claim-preview--channel_.channel-thumbnail]:size-[2.5rem] tw:[&_.claim-preview--channel_.claim-preview\_\_title]:mt-[4px] tw:[&_.claim-preview--channel_.claim-preview\_\_title]:!text-app-small tw:[&_.claim-preview--channel_.claim-preview\_\_title]:!leading-[var(--font-small)] tw:[&_.claim-preview--channel_.claim-preview\_\_title]:text-[rgba(var(--color-text-base),0.8)] tw:[&_.claim-preview--channel_.claim-preview\_\_title:hover]:text-[rgba(var(--color-text-base),1)] tw:[&_.claim-preview--channel_.claim-tile\_\_info]:mt-0 tw:[&_.claim-preview--channel_.claim-tile\_\_info]:pb-0 tw:[&_.claim-preview--channel_.claim-tile\_\_info_.icon]:mb-[-2px] tw:[&_.claim-preview--channel_.claim-tile\_\_info_.icon]:h-[14px] tw:[&_.claim-preview--channel_.claim-preview\_\_actions_button]:!mt-0 tw:[&_.claim-preview--channel_.claim-preview\_\_actions_button]:text-app-body tw:[&_.claim-preview--channel_.claim-preview\_\_actions_button_span]:items-center tw:[&_.claim-preview--channel_.claim-preview\_\_actions_.button-group_a.button]:mt-0 tw:[&_.claim-preview--channel_.claim-preview\_\_actions_.button-group_a.button_.button-surface\_\_content]:!items-center tw:[&_.claim-preview--channel_.claim-preview\_\_actions_.button-group_a.button_.button-surface\_\_content]:mt-0 tw:[&_.claim-preview--channel_.claim-preview\_\_actions_.button-group_a.button_.button-surface\_\_label]:mt-[2px] tw:[&_.claim-preview--channel_.claim-preview\_\_actions_.button-group_a.button_.button-surface\_\_label]:text-app-body tw:[&_.visibility_svg]:mr-app-s tw:[&_.visibility_svg]:size-[2rem] tw:[&_.visibility_svg]:rounded-[50%] tw:[&_.visibility_svg]:bg-app-text tw:[&_.visibility_svg]:p-app-xxs tw:[&_.visibility_svg]:stroke-app-background`,
  subtitle: 'tw:mb-app-s tw:flex tw:justify-between',
  titleText: String.raw`card-title__text tw:!mr-0 tw:flex tw:items-center tw:text-app-large tw:font-bold tw:[word-break:break-word] tw:[&>*:not(:last-child)]:mr-app-s tw:[&_:is(.badge,.tag)]:float-right tw:[&_:is(.badge,.tag)]:mt-[8px] tw:[&_:is(.badge,.tag)]:ml-app-s tw:[&_img]:h-[var(--font-large)] tw:[&_svg]:!mr-0 tw:[&_svg]:size-8 tw:[&_svg]:rounded-[50%] tw:[&_svg]:bg-app-text tw:[&_svg]:p-app-xxs tw:[&_svg]:stroke-app-background tw:[&_:is(label,.confirm\_\_label)]:mt-app-s tw:[&_:is(label,.confirm\_\_label)]:flex-1 tw:[&_:is(label,.confirm\_\_label)]:pl-[10px] tw:[&_:is(label,.confirm\_\_label)]:text-app-large tw:[&_:is(label,.confirm\_\_label)]:font-bold`,
  actions: String.raw`collection-header__actions tw:mb-app-s tw:ml-auto tw:[&_:is(.button,.menu\_\_button)]:bg-[rgba(var(--color-background-base),0.8)] tw:[&_:is(.button,.menu\_\_button)]:p-app-s tw:[&_:is(.button,.menu\_\_button):hover]:bg-[rgba(var(--color-background-base),1)] tw:[&_.menu\_\_button]:rounded-app tw:[&_.menu\_\_button]:!p-[10px] tw:[&_.menu\_\_button]:opacity-100 tw:[&_.menu\_\_button[aria-expanded=true]]:bg-app-background tw:[&_.menu\_\_button[aria-expanded=true]_.icon]:stroke-app-primary tw:upto-small:[&_div:first-child]:flex tw:upto-small:[&_div:first-child]:flex-col-reverse tw:upto-small:[&_div:first-child]:[align-items:end] tw:upto-small:[&_div:first-child_.button]:mt-app-xxs tw:upto-small:[&_div:first-child_.button]:mr-[unset]`,
  description:
    'collection-header__description tw:rounded-app tw:bg-[rgba(var(--color-background-base),0.6)] tw:p-app-s tw:text-app-small tw:upto-small:p-app-xxs',
  meta: 'collection-header__meta tw:mt-app-m tw:flex tw:w-full tw:justify-center tw:gap-app-s tw:upto-small:mt-app-xxs tw:upto-small:flex-wrap tw:upto-small:gap-app-xxs',
  metaEntry: String.raw`collection-header__meta-entry tw:flex-1 tw:items-center tw:rounded-app tw:bg-fixed tw:bg-[length:120%] tw:bg-center tw:bg-no-repeat tw:text-center tw:[&_>div]:flex tw:[&_>div]:h-full tw:[&_>div]:items-center tw:[&_>div]:justify-center tw:[&_>div]:rounded-app tw:[&_>div]:bg-[rgba(var(--color-header-button-base),0.8)] tw:[&_>div]:p-app-s tw:[&_.icon]:mr-app-xxs tw:upto-small:box-border tw:upto-small:grow tw:upto-small:[flex:1_0_40%] tw:upto-small:[&_>div]:!text-app-xxsmall tw:upto-small:[&_>div]:p-app-xxs tw:upto-small:[&_>div_span]:!text-app-xxsmall tw:upto-small:[&_>div_svg]:!mr-app-xxxs tw:upto-small:[&_>div_svg]:!mb-[-2px] tw:upto-small:[&_>div_svg]:size-[10px]`,
} as const;

export const COLLECTION_ACTIONS_CLASS = String.raw`collection-actions tw:sticky tw:top-[var(--header-height)] tw:z-[7] tw:mb-app-l tw:border-b tw:border-b-[var(--color-header-button)] tw:bg-app-header tw:[-webkit-backdrop-filter:blur(4px)] tw:[backdrop-filter:blur(4px)] tw:after:absolute tw:after:bottom-[-20px] tw:after:z-[7] tw:after:h-[20px] tw:after:w-full tw:after:bg-[linear-gradient(180deg,var(--color-background)_0,transparent_35%)] tw:after:content-[''] tw:[&_.section\_\_actions]:grow tw:[&_.section\_\_actions_.ratio-wrapper]:mx-app-m tw:[&_.section\_\_actions_.ratio-wrapper]:!mr-app-m tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button])]:my-app-s tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button])]:bg-[var(--color-header-button)] tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button])]:p-app-s tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button]):hover]:!bg-app-primary tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button]):hover_:is(.button-surface\_\_label,.icon)]:text-app-primary-contrast tw:[&_.section\_\_actions_button:not(.reaction-button-surface--like):not(.reaction-button-surface--dislike):not(.button-toggle-surface):not([data-reach-menu-button]):hover_.icon]:stroke-app-primary-contrast tw:[&_.section\_\_actions_.button-toggle-surface]:!mr-0 tw:[&_.section\_\_actions_.button-toggle-surface]:!bg-[var(--color-header-button)] tw:[&_.section\_\_actions_.button-toggle-surface:hover]:!bg-app-primary tw:[&_.section\_\_actions:last-of-type]:[justify-content:end] tw:[&_.section\_\_actions:first-of-type]:[justify-content:start] tw:upto-small:top-[var(--header-height-mobile)] tw:upto-small:!mb-app-l tw:upto-small:after:hidden tw:upto-small:[&_.section\_\_actions]:!m-0 tw:upto-small:[&_.button]:bg-[var(--color-header-button)]`;
