export const VIDEO_FULLSCREEN_ACTIONS_WRAPPER_CLASS =
  'video-fullscreen__actions-wrapper tw:hidden tw:active-player-fullscreen:contents';

export const VIDEO_FULLSCREEN_ACTIONS_CLASS = String.raw`video-fullscreen__actions tw:[--player-surface-bg:oklch(0%_0_0deg_/_0.4)] tw:[--player-overlay-bg:oklch(20%_0_0deg_/_0.65)] tw:[--player-hover-bg:oklch(from_currentColor_l_c_h_/_0.1)] tw:[--media-surface-background-color:var(--player-surface-bg)] tw:active-player-fullscreen:pointer-events-none tw:active-player-fullscreen:fixed tw:active-player-fullscreen:top-1/2 tw:active-player-fullscreen:right-[24px] tw:active-player-fullscreen:z-[100] tw:active-player-fullscreen:flex tw:active-player-fullscreen:[transform:translateY(-50%)] tw:active-player-fullscreen:flex-col tw:active-player-fullscreen:items-center tw:active-player-fullscreen:gap-[0.5rem] tw:active-player-fullscreen:opacity-0 tw:active-player-fullscreen:[transition:opacity_300ms_ease-out_500ms,right_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:[@media(pointer:coarse)]:active-player-fullscreen-actions-coarse-revealed:pointer-events-auto tw:[@media(pointer:coarse)]:active-player-fullscreen-actions-coarse-revealed:opacity-100 tw:[@media(pointer:coarse)]:active-player-fullscreen-actions-coarse-revealed:[transition:opacity_100ms_ease-out_0ms,right_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:[@media(pointer:fine)]:active-player-fullscreen-actions-fine-revealed:pointer-events-auto tw:[@media(pointer:fine)]:active-player-fullscreen-actions-fine-revealed:opacity-100 tw:[@media(pointer:fine)]:active-player-fullscreen-actions-fine-revealed:[transition:opacity_100ms_ease-out_0ms,right_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:active-player-fullscreen:[&[data-mobile-hidden]]:!pointer-events-none tw:active-player-fullscreen:[&[data-mobile-hidden]]:!opacity-0 tw:active-player-fullscreen:[&[data-mobile-hidden]]:![transition:opacity_50ms_ease-out_0ms,right_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:upto-small:active-player-fullscreen:top-auto tw:upto-small:active-player-fullscreen:right-[8px] tw:upto-small:active-player-fullscreen:bottom-[68px] tw:upto-small:active-player-fullscreen:[transform:none] tw:upto-small:active-player-fullscreen:flex-row tw:upto-small:active-player-fullscreen:[&_.video-fullscreen\_\_action-btn:not(.video-fullscreen\_\_action-btn--reaction)]:hidden`;

export const VIDEO_FULLSCREEN_ACTIONS_GROUP_CLASS =
  'video-fullscreen__actions-group tw:active-player-fullscreen:flex tw:active-player-fullscreen:flex-col tw:active-player-fullscreen:items-center tw:active-player-fullscreen:gap-[0.075rem] tw:active-player-fullscreen:rounded-[9999px] tw:active-player-fullscreen:bg-[var(--player-overlay-bg)] tw:active-player-fullscreen:p-[0.25rem]';

export const VIDEO_FULLSCREEN_ACTION_BUTTON_CLASS = String.raw`video-fullscreen__action-btn tw:active-player-fullscreen:relative tw:active-player-fullscreen:flex tw:active-player-fullscreen:!size-[2.125rem] tw:active-player-fullscreen:min-h-[2.125rem] tw:active-player-fullscreen:min-w-[2.125rem] tw:active-player-fullscreen:cursor-pointer tw:active-player-fullscreen:items-center tw:active-player-fullscreen:justify-center tw:active-player-fullscreen:overflow-visible tw:active-player-fullscreen:!rounded-[9999px] tw:active-player-fullscreen:!border-none tw:active-player-fullscreen:bg-transparent tw:active-player-fullscreen:!p-0 tw:active-player-fullscreen:!m-0 tw:active-player-fullscreen:text-white tw:active-player-fullscreen:![box-shadow:none] tw:active-player-fullscreen:[backdrop-filter:none] tw:active-player-fullscreen:[transition:background-color_150ms_ease] tw:active-player-fullscreen:hover:!bg-[oklch(100%_0_0deg_/_0.2)] tw:active-player-fullscreen:[&_.button-surface\_\_content]:flex tw:active-player-fullscreen:[&_.button-surface\_\_content]:items-center tw:active-player-fullscreen:[&_.button-surface\_\_content]:justify-center tw:active-player-fullscreen:[&_.button-surface\_\_content]:gap-0 tw:active-player-fullscreen:[&_.button-surface\_\_content]:p-0 tw:active-player-fullscreen:[&_.button-surface\_\_label]:contents tw:active-player-fullscreen:[&_.button\_\_fire-glow]:bottom-1/2 tw:active-player-fullscreen:[&_.button\_\_fire-glow]:left-1/2 tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle1,.button\_\_fire-particle4)]:left-1/2 tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle1,.button\_\_fire-particle4)]:right-auto tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle1,.button\_\_fire-particle4)]:![animation-name:particleUpCenter1] tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle2,.button\_\_fire-particle5)]:left-1/2 tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle2,.button\_\_fire-particle5)]:right-auto tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle2,.button\_\_fire-particle5)]:![animation-name:particleUpCenter2] tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle3,.button\_\_fire-particle6)]:left-1/2 tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle3,.button\_\_fire-particle6)]:right-auto tw:active-player-fullscreen:[&_:is(.button\_\_fire-particle3,.button\_\_fire-particle6)]:![animation-name:particleUpCenter3] tw:active-player-fullscreen:[&_[class^='button\_\_slime']]:bottom-1/2 tw:active-player-fullscreen:[&_[class^='button\_\_slime']]:left-1/2 tw:active-player-fullscreen:[&_.icon]:size-[16px] tw:active-player-fullscreen:[&_.icon]:stroke-white tw:active-player-fullscreen:[&_.icon]:[filter:drop-shadow(0_1px_0_oklch(0%_0_0deg_/_0.25))]`;

export const VIDEO_FULLSCREEN_ACTION_BUTTON_ACTIVE_CLASS =
  'video-fullscreen__action-btn--active tw:active-player-fullscreen:!bg-[var(--color-primary)] tw:active-player-fullscreen:hover:!bg-[var(--color-primary)]';

export const VIDEO_FULLSCREEN_ACTION_BUTTON_REACTION_CLASS = 'video-fullscreen__action-btn--reaction';

export const VIDEO_FULLSCREEN_SHORTS_ACTIONS_CLASS = String.raw`video-fullscreen__actions--shorts tw:active-player-fullscreen:!pointer-events-auto tw:active-player-fullscreen:gap-0 tw:active-player-fullscreen:!opacity-100 tw:active-player-fullscreen:rounded-none tw:active-player-fullscreen:bg-none tw:active-player-fullscreen:p-0 tw:active-player-fullscreen:[&.video-fullscreen\_\_actions--shorts[data-mobile-hidden]]:!pointer-events-auto tw:active-player-fullscreen:[&.video-fullscreen\_\_actions--shorts[data-mobile-hidden]]:!opacity-100`;

export const VIDEO_FULLSCREEN_ACTIONS_LANDSCAPE_CLASS = 'video-fullscreen__actions-wrapper--landscape';

export const VIDEO_FULLSCREEN_SIDE_PANEL_CLASS = String.raw`video-fullscreen__side-panel tw:hidden tw:active-player-fullscreen:fixed tw:active-player-fullscreen:top-0 tw:active-player-fullscreen:right-[-720px] tw:active-player-fullscreen:z-[200] tw:active-player-fullscreen:flex tw:active-player-fullscreen:h-full tw:active-player-fullscreen:w-[720px] tw:active-player-fullscreen:flex-col tw:active-player-fullscreen:overflow-hidden tw:active-player-fullscreen:[background:var(--color-background)] tw:active-player-fullscreen:[transition:right_0.3s_cubic-bezier(0.4,0,0.2,1),width_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:active-fullscreen-landscape:right-[calc(var(--video-fullscreen-side-panel-width)*-1)] tw:active-fullscreen-landscape:w-[var(--video-fullscreen-side-panel-width)] tw:active-fullscreen-landscape:flex-row`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_OPEN_CLASS =
  'video-fullscreen__side-panel--open tw:active-player-fullscreen:!right-0';

export const VIDEO_FULLSCREEN_SIDE_PANEL_PLAYLIST_CLASS = String.raw`video-fullscreen__side-panel--playlist tw:active-player-fullscreen:right-[-720px] tw:active-player-fullscreen:w-[720px] tw:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--open]:!right-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_close-button-container]:hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex-col tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:overflow-y-hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:p-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content_.card\_\_header--between]:mt-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content_.card\_\_header--between]:pr-[6.4px]`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_CHAPTERS_CLASS = String.raw`video-fullscreen__side-panel--chapters tw:active-player-fullscreen:[&_.video-fullscreen\_\_close-button-container]:hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex-col tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:overflow-y-hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:p-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content_.card\_\_header--between]:mt-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content_.card\_\_header--between]:pr-[6.4px]`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_CHAT_CLASS = String.raw`video-fullscreen__side-panel--chat tw:active-player-fullscreen:fixed tw:active-player-fullscreen:right-[calc((var(--livestream-comments-width)+var(--spacing-m))*-1)] tw:active-player-fullscreen:w-[calc(var(--livestream-comments-width)+var(--spacing-m))] tw:active-player-fullscreen:overflow-hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_close-button-container]:hidden tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:relative tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:min-h-0 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex-1 tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:flex-col tw:active-player-fullscreen:[&_.video-fullscreen\_\_side-panel-content]:p-0`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_MOBILE_CLASS = String.raw`video-fullscreen__side-panel--mobile tw:upto-small:active-player-fullscreen:top-auto tw:upto-small:active-player-fullscreen:right-0 tw:upto-small:active-player-fullscreen:bottom-0 tw:upto-small:active-player-fullscreen:left-0 tw:upto-small:active-player-fullscreen:h-[calc(100dvh-56.25vw)] tw:upto-small:active-player-fullscreen:w-full tw:upto-small:active-player-fullscreen:[transform:translateY(100%)] tw:upto-small:active-player-fullscreen:![transition:transform_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:upto-small:active-player-fullscreen:[border-radius:12px_12px_0_0] tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--open]:[transform:translateY(0)] tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--chat]:right-0 tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--chat]:h-[calc(100dvh-56.25vw)] tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--chat]:w-full tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--chat.video-fullscreen\_\_side-panel--open]:right-0 tw:upto-small:active-player-fullscreen:[&.video-fullscreen\_\_side-panel--chat.video-fullscreen\_\_side-panel--open]:[transform:translateY(0)]`;

export const VIDEO_FULLSCREEN_SIDE_HANDLE_CLASS = String.raw`video-fullscreen__side-handle tw:active-fullscreen-landscape:flex tw:active-fullscreen-landscape:w-[16px] tw:active-fullscreen-landscape:flex-shrink-0 tw:active-fullscreen-landscape:cursor-grab tw:active-fullscreen-landscape:items-center tw:active-fullscreen-landscape:justify-center tw:active-fullscreen-landscape:border-r tw:active-fullscreen-landscape:border-r-[rgba(255,255,255,0.1)] tw:active-fullscreen-landscape:[touch-action:none]`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_INNER_CLASS = String.raw`video-fullscreen__side-panel-inner tw:active-fullscreen-landscape:flex tw:active-fullscreen-landscape:min-w-0 tw:active-fullscreen-landscape:flex-1 tw:active-fullscreen-landscape:flex-col tw:active-fullscreen-landscape:overflow-y-auto tw:active-fullscreen-landscape:[&_.tag]:h-[var(--height-badge)] tw:active-fullscreen-landscape:[&_.tag]:p-app-xs tw:active-fullscreen-landscape:[&_.tag]:text-app-xsmall`;

export const VIDEO_FULLSCREEN_PULLER_CLASS = String.raw`video-fullscreen__puller tw:upto-small:active-player-fullscreen:mx-auto tw:upto-small:active-player-fullscreen:my-[8px] tw:upto-small:active-player-fullscreen:block tw:upto-small:active-player-fullscreen:h-[4px] tw:upto-small:active-player-fullscreen:w-[32px] tw:upto-small:active-player-fullscreen:rounded-[2px] tw:upto-small:active-player-fullscreen:bg-app-text tw:upto-small:active-player-fullscreen:opacity-30`;

export const VIDEO_FULLSCREEN_PULLER_VERTICAL_CLASS = String.raw`video-fullscreen__puller--vertical tw:active-fullscreen-landscape:h-[32px] tw:active-fullscreen-landscape:w-[4px] tw:active-fullscreen-landscape:rounded-[2px] tw:active-fullscreen-landscape:bg-app-text tw:active-fullscreen-landscape:opacity-30`;

export const VIDEO_FULLSCREEN_SHEET_HEADER_CLASS = String.raw`video-fullscreen__sheet-header tw:upto-small:active-player-fullscreen:flex tw:upto-small:active-player-fullscreen:flex-shrink-0 tw:upto-small:active-player-fullscreen:flex-col tw:upto-small:active-player-fullscreen:items-center tw:upto-small:active-player-fullscreen:pb-[8px] tw:upto-small:active-player-fullscreen:[touch-action:none]`;

export const VIDEO_FULLSCREEN_CLOSE_BUTTON_CONTAINER_CLASS =
  'video-fullscreen__close-button-container tw:active-player-fullscreen:absolute tw:active-player-fullscreen:top-[20px] tw:active-player-fullscreen:right-[38px] tw:active-player-fullscreen:z-[1]';

export const VIDEO_FULLSCREEN_CLOSE_BUTTON_CLASS = String.raw`video-fullscreen__close-button tw:active-player-fullscreen:cursor-pointer tw:active-player-fullscreen:!rounded-[50%] tw:active-player-fullscreen:!border-none tw:active-player-fullscreen:[background:rgba(128,128,128,0.2)] tw:active-player-fullscreen:!p-[10px] tw:active-player-fullscreen:text-app-text tw:active-player-fullscreen:hover:![background:var(--color-primary)] tw:upto-small:active-player-fullscreen:[.video-fullscreen\_\_sheet-header_&]:mr-[8px] tw:upto-small:active-player-fullscreen:[.video-fullscreen\_\_sheet-header_&]:self-end`;

export const VIDEO_FULLSCREEN_CHAT_CLOSE_BUTTON_CLASS = String.raw`video-fullscreen__chat-close-button tw:active-player-fullscreen:absolute tw:active-player-fullscreen:top-app-xs tw:active-player-fullscreen:right-app-xxs tw:active-player-fullscreen:z-[2] tw:active-player-fullscreen:flex tw:active-player-fullscreen:cursor-pointer tw:active-player-fullscreen:items-center tw:active-player-fullscreen:justify-center tw:active-player-fullscreen:rounded-[50%] tw:active-player-fullscreen:border-none tw:active-player-fullscreen:bg-app-background tw:active-player-fullscreen:p-[8px] tw:active-player-fullscreen:[transition:background-color_0.2s] tw:active-player-fullscreen:[&_.icon]:stroke-app-text tw:active-player-fullscreen:hover:bg-app-primary tw:active-player-fullscreen:hover:[&_.icon]:stroke-app-primary-contrast`;

export const VIDEO_FULLSCREEN_SIDE_PANEL_CONTENT_CLASS = String.raw`video-fullscreen__side-panel-content tw:active-player-fullscreen:min-h-0 tw:active-player-fullscreen:flex-1 tw:active-player-fullscreen:overflow-x-hidden tw:active-player-fullscreen:overflow-y-scroll tw:active-player-fullscreen:[padding:4px_24px_24px]`;
