export const HEADER_NOTIFICATION_CLASSES = {
  menu: String.raw`menu__list--notifications tw:[&_.MuiMenu-list]:p-0 tw:[&_.MuiMenu-list]:![backdrop-filter:blur(4px)] tw:[&_.MuiMenu-list]:!bg-[unset] tw:[&_.header-notification-drawer\_\_paper]:![background-color:unset]`,
  paper: 'header-notification-drawer__paper tw:rounded-t-none tw:rounded-b-app tw:!bg-[unset]',
  push: String.raw`menu__list--notifications-push tw:absolute tw:top-1/2 tw:right-app-s tw:whitespace-nowrap tw:!text-[11px] tw:opacity-45 tw:[transform:translateY(-50%)] tw:hover:opacity-100 tw:[&_.icon]:size-[12px]`,
  list: String.raw`menu__list--notifications-list tw:max-h-[388px] tw:overflow-y-scroll tw:bg-app-header tw:[&::-webkit-scrollbar-track]:bg-[rgba(var(--color-header-background-base),0.8)]`,
  row: String.raw`menu__list--notification tw:relative tw:flex tw:w-[440px] tw:overflow-hidden tw:[border-top:1px_solid_var(--color-header-background)] tw:bg-[var(--color-header-button)] tw:p-app-s tw:[transition:border-left_0.4s] tw:hover:cursor-pointer tw:hover:bg-[rgba(var(--color-header-background-base),1)] tw:hover:[&_.notification\_\_icon_.icon\_\_wrapper]:bg-[var(--color-header-button)] tw:hover:[&_.notification\_\_icon_.icon\_\_wrapper]:text-app-text tw:hover:[&_.menu\_\_list--notification-title_.notification\_\_text]:text-app-primary tw:hover:[&_.menu\_\_list--notification-title_.notification\_\_text_blockquote]:!text-app-primary tw:hover:[&_.delete-notification]:opacity-100`,
  rowWithOverlay: String.raw`menu__list--notification--with-overlay tw:pointer-events-none tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore],.delete-notification)]:pointer-events-auto tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore],.delete-notification)]:relative tw:[&_:is(a:not(.notification\_\_link-overlay),button,input,select,textarea,[role='button'],[data-notification-ignore],.delete-notification)]:z-[2]`,
  unread: 'menu__list--notification-unread tw:[border-left:2px_solid_var(--color-primary)]',
  icon: String.raw`tw:!mt-0 tw:!ml-0 tw:[&_.icon\_\_wrapper]:text-app-text`,
  channelThumbnail: String.raw`tw:!mr-app-s tw:!size-[3rem] tw:[&_img]:size-[3rem] tw:[&_img]:rounded-[50%] tw:[&_canvas]:size-[3rem] tw:[&_canvas]:rounded-[50%]`,
  info: String.raw`menu__list--notification-info tw:w-full tw:overflow-hidden tw:[&_.date\_time.date\_time]:!text-[rgba(var(--color-text-base),0.6)] tw:[&_span]:mr-app-xxxs tw:[&_span]:inline-block tw:[&_span]:text-app-xxsmall tw:[&_span]:text-app-primary tw:[&_span.dot]:text-app-small tw:[&_.sticker\_\_comment]:ml-0 tw:[&_.sticker\_\_comment]:h-[50px] tw:[&_.sticker\_\_comment]:p-app-xxs tw:[&_.sticker\_\_comment]:pl-0`,
  type: String.raw`menu__list--notification-type tw:flex tw:w-full tw:flex-wrap tw:gap-app-xxxs tw:text-app-xsmall tw:text-[rgba(var(--color-text-base),0.6)] tw:[&_.notification\_\_claim-title]:block tw:[&_.notification\_\_claim-title]:w-full tw:[&_.notification\_\_claim-title]:flex-1 tw:[&_.notification\_\_claim-title]:overflow-hidden tw:[&_.notification\_\_claim-title]:text-ellipsis tw:[&_.notification\_\_claim-title]:whitespace-nowrap tw:[&_.notification\_\_claim-title]:text-app-xsmall tw:[&_.notification\_\_claim-title]:font-normal tw:[&_.notification\_\_claim-title]:text-[rgba(var(--color-text-base),0.6)] tw:[&_.button-surface\_\_content]:m-0 tw:[&_.button-surface\_\_content]:flex tw:[&_.button-surface\_\_content_.channel-name]:m-0 tw:[&_.button-surface\_\_content_.channel-name]:text-app-xsmall tw:[&_.button-surface\_\_content_.channel-name]:font-normal tw:[&_.button-surface\_\_content_.channel-name]:text-[rgba(var(--color-text-base),0.6)] tw:[&_.button-surface\_\_content_.channel-name_p:hover]:text-[rgba(var(--color-text-base),1)] tw:[&_.comment\_\_badge]:hidden tw:[&_.comment\_\_badge]:pr-0 tw:[&_span]:!mr-0 tw:[&_span_.credit-amount]:text-app-xsmall tw:[&_span_.credit-amount]:font-normal tw:[&_span_.credit-amount]:text-[rgba(var(--color-text-base),0.6)] tw:[&_span_.credit-amount_svg]:mb-0`,
  title: String.raw`menu__list--notification-title tw:mb-[-3px] tw:w-full tw:grow tw:text-app-text tw:[&_.notification\_\_text]:block tw:[&_.notification\_\_text]:w-full tw:[&_.notification\_\_text]:overflow-hidden tw:[&_.notification\_\_text]:text-ellipsis tw:[&_.notification\_\_text]:whitespace-nowrap tw:[&_.notification\_\_text_blockquote]:block tw:[&_.notification\_\_text_blockquote]:w-full tw:[&_.notification\_\_text_blockquote]:overflow-hidden tw:[&_.notification\_\_text_blockquote]:text-ellipsis tw:[&_.notification\_\_text_blockquote]:whitespace-nowrap tw:[&_.notification\_\_text_blockquote]:pr-0`,
  delete: String.raw`delete-notification tw:pointer-events-auto tw:absolute tw:top-app-xs tw:right-app-xxs tw:z-[2] tw:opacity-0 tw:[&_.icon\_\_wrapper]:size-[20px] tw:[&_.icon\_\_wrapper]:bg-[rgba(var(--color-header-button-base),0.95)] tw:[&_.icon\_\_wrapper]:p-0 tw:[&_.icon\_\_wrapper]:[outline:4px_solid_rgba(var(--color-header-background-base),1)] tw:[&_.icon\_\_wrapper_svg]:size-[12px] tw:hover:[&_.icon\_\_wrapper]:bg-app-primary tw:hover:[&_.icon\_\_wrapper_.icon]:stroke-[var(--color-primary-contrast)]`,
  empty:
    'menu__list--notification-empty tw:block tw:w-[440px] tw:whitespace-normal tw:bg-[rgba(var(--color-header-button-base),0.95)] tw:px-app-s tw:py-app-m tw:text-center tw:text-app-text tw:[overflow-wrap:break-word]',
  emptyTitle: 'menu__list--notification-empty-title tw:text-app-body tw:font-bold',
  emptyText:
    'menu__list--notification-empty-text tw:text-app-xsmall tw:font-normal tw:text-[rgba(var(--color-text-base),0.6)]',
  more: String.raw`menu__list--notifications-more tw:relative tw:[border-top:1px_solid_rgba(var(--color-header-button-base),0.95)] tw:bg-[rgba(var(--color-header-background-base),1)] tw:px-app-xs tw:py-app-s tw:text-center tw:text-app-text tw:hover:cursor-pointer tw:hover:text-app-primary`,
} as const;
