const MOBILE_TAB_PANEL_BASE_CLASS = String.raw`mobile-tab-view__panel tw:h-full tw:flex-[0_0_100%] tw:overflow-y-auto tw:p-app-xxs tw:[overscroll-behavior:contain] tw:[scrollbar-width:none] tw:[&::-webkit-scrollbar]:hidden tw:[&_.comment\_\_list]:overflow-visible tw:[&:has(.chat\_\_wrapper)]:p-0 tw:[&_.card\_\_first-pane]:pb-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))]`;

const MOBILE_TAB_PANEL_COMPACT_CLASS = String.raw`mobile-tab-panel-compact-surface tw:upto-small:[&_.file-page\_\_recommended]:pt-0 tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:sticky tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:top-[calc(var(--spacing-xxs)*-1)] tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:z-[7] tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:mx-[calc(var(--spacing-xxs)*-1)] tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:bg-app-header tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:px-app-xxs tw:upto-small:[&_.file-page\_\_recommended_.card\_\_header--between]:py-app-xs tw:upto-small:[&_.file-page\_\_recommended_.card\_\_first-pane]:pt-0 tw:upto-small:[&_.file-page\_\_recommended_.media\_\_thumb]:!w-[calc(var(--file-list-thumbnail-width)*0.8)] tw:upto-small:[&:has(.chat\_\_wrapper)]:overflow-hidden tw:upto-small:[&:has(.chat\_\_wrapper)]:pb-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))] tw:upto-small:[&_.chat\_\_wrapper]:m-0 tw:upto-small:[&_.chat\_\_wrapper]:flex tw:upto-small:[&_.chat\_\_wrapper]:h-full tw:upto-small:[&_.chat\_\_wrapper]:flex-col tw:upto-small:[&_.chat\_\_wrapper]:rounded-none tw:upto-small:[&_.chat\_\_wrapper]:border-none tw:upto-small:[&_.chat\_\_wrapper]:[border-color:currentColor] tw:upto-small:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:h-0 tw:upto-small:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:min-h-0 tw:upto-small:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:flex-1 tw:upto-small:[&_.chat\_\_wrapper_.livestream\_\_comments--mobile]:px-app-xxs tw:upto-small:[&_.playlist\_\_wrapper_.card\_\_body_[data-claim-list]_.ul--no-style]:pb-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))] tw:upto-small:[&_.chapters-card]:rounded-none tw:upto-small:[&_.chapters-card]:[background:none] tw:upto-small:[&_.chapters-card]:p-0 tw:upto-small:[&_.chapters-card_.card\_\_title-actions-container]:hidden tw:upto-small:[&_.chapters-card_.card\_\_header--slim]:p-app-xxs tw:upto-small:[&_.chapters-card_.chapters-card\_\_list]:rounded-none`;

const MOBILE_TAB_PANEL_SHEET_CLASS = String.raw`tw:[.mobile-tab-view\_\_sheet_&]:h-full tw:[.mobile-tab-view\_\_sheet_&]:min-w-0 tw:[.mobile-tab-view\_\_sheet_&]:w-full tw:[.mobile-tab-view\_\_sheet_&:first-child]:pt-app-xs tw:[.mobile-tab-view\_\_sheet_&:has(.chat\_\_wrapper)]:overflow-hidden tw:[.mobile-tab-view\_\_sheet_&:has(.chat\_\_wrapper)]:pb-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))] tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:m-0 tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:flex tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:h-full tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:flex-col tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:rounded-none tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:border-none tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper]:[border-color:currentColor] tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:h-0 tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:min-h-0 tw:[.mobile-tab-view\_\_sheet_&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:flex-1 tw:[.mobile-tab-view\_\_sheet_&_.file-page\_\_recommended]:mt-0 tw:[.mobile-tab-view\_\_sheet_&_.file-page\_\_recommended_.card\_\_header--between]:pt-app-xs`;

const MOBILE_TAB_PANEL_FULLSCREEN_CHAT_CLASS = String.raw`tw:active-fullscreen-side-panel:[&:has(.chat\_\_wrapper)]:overflow-hidden tw:active-fullscreen-side-panel:[&:has(.chat\_\_wrapper)]:pb-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))] tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:m-0 tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:flex tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:h-full tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:flex-col tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:rounded-none tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper]:![border:none] tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:h-0 tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:min-h-0 tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper_.livestream-comments\_\_wrapper]:flex-1 tw:active-fullscreen-side-panel:[&_.chat\_\_wrapper_.livestream\_\_comments--mobile]:px-app-xxs`;

export const MOBILE_TAB_VIEW_CLASSES = {
  root: 'mobile-tab-view tw:flex tw:w-full tw:flex-col',
  scrollContainer: String.raw`mobile-tab-view__scroll-container tw:overflow-hidden tw:[.mobile-tab-view\_\_sheet_&]:w-full tw:[.mobile-tab-view\_\_sheet_&]:min-h-0 tw:[.mobile-tab-view\_\_sheet_&]:flex-1`,
  track: 'mobile-tab-view__track tw:flex tw:h-full tw:will-change-transform',
  panel: `${MOBILE_TAB_PANEL_BASE_CLASS} ${MOBILE_TAB_PANEL_COMPACT_CLASS} ${MOBILE_TAB_PANEL_SHEET_CLASS} ${MOBILE_TAB_PANEL_FULLSCREEN_CHAT_CLASS}`,
  bar: String.raw`mobile-tab-view__bar tw:fixed tw:right-0 tw:bottom-0 tw:left-0 tw:z-[5] tw:flex tw:h-[calc(var(--header-height-mobile)+env(safe-area-inset-bottom,0px))] tw:items-center tw:justify-around tw:border-t tw:border-t-app-border tw:bg-[color-mix(in_srgb,var(--color-header-background)_80%,transparent)] tw:pb-[env(safe-area-inset-bottom,0px)] tw:[-webkit-backdrop-filter:blur(8px)] tw:[backdrop-filter:blur(8px)] tw:[.mobile-tab-view\_\_sheet_&]:!absolute`,
  tab: String.raw`mobile-tab-view__tab tw:flex tw:cursor-pointer tw:flex-col tw:items-center tw:gap-[2px] tw:border-none tw:[background:none] tw:px-app-m tw:py-app-xxs tw:text-app-text-subtitle tw:[transition:color_var(--animation-duration)_var(--animation-style)]`,
  tabActive: 'mobile-tab-view__tab--active tw:!text-app-primary',
  tabLabel: 'mobile-tab-view__tab-label tw:text-app-xxsmall tw:[font-weight:var(--font-weight-bold)]',
  drawer: 'mobile-tab-view--drawer tw:pointer-events-none tw:absolute tw:inset-0 tw:overflow-hidden',
  sheet: String.raw`mobile-tab-view__sheet tw:pointer-events-auto tw:absolute tw:right-0 tw:bottom-0 tw:left-0 tw:z-[101] tw:flex tw:h-[calc(100%_-_56.25vw)] tw:flex-col tw:overflow-hidden tw:rounded-t-[12px] tw:bg-app-background tw:[transform:translateY(100%)] tw:[transition:transform_0.2s_ease] tw:[.player-fullscreen-target--no-transition_&]:![transition:none]`,
  sheetOpen: 'mobile-tab-view__sheet--open tw:![transform:translateY(0)]',
  sheetHeader:
    'mobile-tab-view__sheet-header tw:flex tw:shrink-0 tw:cursor-grab tw:justify-center tw:border-b tw:border-b-app-border tw:px-0 tw:py-app-m tw:[touch-action:none]',
  puller: 'mobile-tab-view__puller tw:h-[4px] tw:w-[30px] tw:rounded-[2px] tw:bg-app-text-subtitle',
} as const;
