const FORM_FIELD_CHARACTER_COUNTER_BASE_CLASS = 'tw:float-right tw:inline tw:!text-app-xsmall tw:opacity-60';

const FORM_CONTROL_CLASS = String.raw`tw:relative tw:flex tw:flex-col tw:last:mb-0 tw:[&_input]:w-full tw:[&_select]:w-full tw:[&_input:is([type='checkbox'],[type='radio'])]:absolute tw:[&_input:is([type='checkbox'],[type='radio'])]:left-0 tw:[&_input:is([type='checkbox'],[type='radio'])]:h-[var(--height-checkbox)] tw:[&_input:is([type='checkbox'],[type='radio'])]:w-[var(--height-checkbox)] tw:[&_input:is([type='checkbox'],[type='radio'])]:border-none tw:[&_input:is([type='checkbox'],[type='radio'])]:bg-transparent tw:[&_input:is([type='checkbox'],[type='radio'])]:p-0 tw:[&_input:is([type='checkbox'],[type='radio']):disabled+:is(label,.confirm\_\_label)]:pointer-events-none tw:[&_input:is([type='checkbox'],[type='radio']):disabled+:is(label,.confirm\_\_label)]:cursor-default tw:[&_:is(label,.confirm\_\_label)]:relative tw:[&_:is(label,.confirm\_\_label)]:m-0 tw:[&_:is(label,.confirm\_\_label)]:inline-block tw:[&_:is(label,.confirm\_\_label)]:min-h-[var(--height-checkbox)] tw:[&_:is(label,.confirm\_\_label)]:pl-[calc(var(--height-checkbox)+var(--spacing-s))] tw:[&_:is(label,.confirm\_\_label)]:[font-size:var(--font-base)] tw:[&_:is(label,.confirm\_\_label)]:[line-height:var(--height-checkbox)] tw:[&_:is(label,.confirm\_\_label)::before]:absolute tw:[&_:is(label,.confirm\_\_label)::before]:top-0 tw:[&_:is(label,.confirm\_\_label)::before]:bg-[var(--color-header-button)] tw:[&_:is(label,.confirm\_\_label)::before]:content-[''] tw:[&_:is(label,.confirm\_\_label)::after]:absolute tw:[&_:is(label,.confirm\_\_label)::after]:content-[''] tw:[&_input:is([type='checkbox'],[type='radio'])+:is(label,.confirm\_\_label)::after]:content-none tw:[&_input:is([type='checkbox'],[type='radio']):checked+:is(label,.confirm\_\_label)::after]:content-['']`;

export const FORM_CHECKBOX_CLASS = String.raw`checkbox ${FORM_CONTROL_CLASS} tw:[&_:is(label,.confirm\_\_label)::before]:left-0 tw:[&_:is(label,.confirm\_\_label)::before]:size-[var(--height-checkbox)] tw:[&_:is(label,.confirm\_\_label)::before]:rounded-app tw:[&_:is(label,.confirm\_\_label)::after]:top-[8px] tw:[&_:is(label,.confirm\_\_label)::after]:left-[6px] tw:[&_:is(label,.confirm\_\_label)::after]:h-[6px] tw:[&_:is(label,.confirm\_\_label)::after]:w-[12px] tw:[&_:is(label,.confirm\_\_label)::after]:[border-left:2px_solid_var(--color-primary)] tw:[&_:is(label,.confirm\_\_label)::after]:[border-bottom:2px_solid_var(--color-primary)] tw:[&_:is(label,.confirm\_\_label)::after]:[transform:rotate(-45deg)] tw:hover:[&_input]:[box-shadow:unset] tw:hover:[&_:is(label,.confirm\_\_label)]:cursor-pointer tw:hover:[&_:is(label,.confirm\_\_label)::before]:[box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset]`;

export const FORM_RADIO_CLASS = String.raw`radio ${FORM_CONTROL_CLASS} tw:[&_input[type='radio']]:rounded-[50%] tw:[&_:is(label,.confirm\_\_label)::before]:left-0 tw:[&_:is(label,.confirm\_\_label)::before]:size-[var(--height-radio)] tw:[&_:is(label,.confirm\_\_label)::before]:rounded-[calc(var(--height-radio)*0.5)] tw:[&_:is(label,.confirm\_\_label)::after]:top-[6px] tw:[&_:is(label,.confirm\_\_label)::after]:left-[6px] tw:[&_:is(label,.confirm\_\_label)::after]:size-[12px] tw:[&_:is(label,.confirm\_\_label)::after]:rounded-[50%] tw:[&_:is(label,.confirm\_\_label)::after]:bg-app-primary tw:hover:[&_:is(label,.confirm\_\_label)]:cursor-pointer tw:hover:[&_:is(label,.confirm\_\_label)::before]:[box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset]`;

export const FORM_FIELD_CHARACTER_COUNTER_CLASS = FORM_FIELD_CHARACTER_COUNTER_BASE_CLASS;
export const FORM_FIELD_CHARACTER_COUNTER_ERROR_CLASS = `${FORM_FIELD_CHARACTER_COUNTER_BASE_CLASS} tw:text-app-text-error`;

export const FORM_FIELD_COMMENT_COUNT_CLASS = String.raw`comment__char-count-mde tw:self-end tw:pr-app-xs tw:pb-0 tw:text-app-xsmall tw:[.MuiPaper-root_&]:![align-self:unset] tw:[.MuiPaper-root_&]:pr-0 tw:[.MuiPaper-root_&]:pt-[2px]`;
export const FORM_FIELD_HINT_CLASS =
  'form-field__hint tw:text-app-small tw:text-[var(--color-input-label)] tw:opacity-80';
export const FORM_FIELD_HINT_COMPACT_CLASS = `${FORM_FIELD_HINT_CLASS} tw:!text-app-xsmall tw:!text-app-text-subtitle`;
export const FORM_FIELD_COPYABLE_CLASS = String.raw`form-field--copyable tw:cursor-default tw:select-text tw:text-ellipsis tw:px-[0.75rem] tw:py-[0.2rem] tw:[&~.button+.button]:ml-px tw:[&~button+button]:ml-px`;
export const FORM_FIELD_PRICE_AMOUNT_CLASS = 'form-field--price-amount tw:max-w-[6em]';
export const FORM_FIELD_ADDRESS_CLASS = 'form-field--address tw:min-w-[18em] tw:[@media(max-width:450px)]:min-w-[10em]';
export const FORM_FIELD_MARKDOWN_CLASS = String.raw`form-field--SimpleMDE tw:mt-[4px] tw:[.channelPage-edit-wrapper_&]:mt-app-m tw:[&_#create\_\_comment-wrapper]:mt-app-xxxxs`;
export const FORM_FIELD_TWO_COLUMN_CLASS = String.raw`form-field__two-column tw:small:[column-count:2] tw:upto-small:[&_span]:text-app-xxsmall`;
export const FORM_FIELD_SLIM_SELECT_CLASS = String.raw`select--slim tw:small:[fieldset-section_&]:max-w-none tw:small:[.fieldset-section_&]:max-w-none tw:[fieldset-section_&_select]:!max-h-[var(--height-input-slim)] tw:[fieldset-section_&_select]:[padding:0_var(--spacing-l)_0_var(--spacing-xs)] tw:[.fieldset-section_&_select]:!max-h-[var(--height-input-slim)] tw:[.fieldset-section_&_select]:[padding:0_var(--spacing-l)_0_var(--spacing-xs)] tw:upto-small:[fieldset-section_&_select]:!max-h-[1.25rem] tw:upto-small:[.fieldset-section_&_select]:!max-h-[1.25rem]`;
export const INPUT_SUBMIT_CLASS = String.raw`input-submit tw:flex tw:items-center tw:[&>:is(*:first-child,*:last-child)]:m-0 tw:[&>*:first-child]:!rounded-r-none tw:[&>*:first-child]:![border-right:none] tw:[&>:not(:first-child):not(:last-child)]:rounded-none tw:[&>*:last-child]:rounded-l-none tw:[&_input]:z-[2]`;
