export const SNACK_BAR_CLASSES = {
  root: String.raw`snack-bar tw:fixed tw:right-[2rem] tw:bottom-[2rem] tw:z-[100001] tw:flex tw:max-w-[20rem] tw:flex-col tw:rounded-app tw:border-2 tw:border-solid tw:border-app-primary tw:bg-[rgba(var(--color-primary-static),0.9)] tw:px-app-m tw:py-app-s tw:text-app-primary-contrast tw:backdrop-blur-[4px] tw:[transition:all_var(--transition-duration)_var(--transition-type)] tw:[&_.button-surface\_\_label]:text-app-primary-contrast tw:[&_.button-surface\_\_content]:p-app-xxxs tw:[&_.button-surface\_\_content_.icon]:[transform:rotate(0deg)] tw:[&_.button-surface\_\_content_.icon]:[transition:transform_0.4s] tw:[&_.button-surface\_\_content:hover]:rounded-app tw:[&_.button-surface\_\_content:hover]:bg-app-background tw:[&_.button-surface\_\_content:hover_.icon]:stroke-app-primary tw:[&_.button-surface\_\_content:hover_.icon]:[transform:rotate(90deg)] tw:upto-small:hidden`,
  error: String.raw`snack-bar--error tw:!border-[red] tw:bg-[var(--color-snack-bg-error)] tw:[&_.button-surface\_\_content:hover_.icon]:!stroke-[var(--color-snack-bg-error)]`,
  counter: String.raw`snack-bar-counter-bubble tw:absolute tw:right-[-6px] tw:bottom-[-6px] tw:flex tw:size-[1.2rem] tw:items-center tw:justify-center tw:rounded-[50%] tw:border-2 tw:border-solid tw:border-app-primary tw:bg-app-background tw:[&_.notification\_\_count]:text-app-xsmall tw:[&_.notification\_\_count]:text-app-text`,
  action: String.raw`snack-bar__action tw:my-app-s tw:ml-auto tw:inline-block tw:min-w-min tw:text-app-small tw:text-app-primary-contrast tw:[&_.button]:rounded-app tw:[&_.button]:border tw:[&_.button]:border-solid tw:[&_.button]:border-current tw:[&_.button]:bg-transparent tw:[&_.button]:text-inherit tw:[&_.button-surface\_\_content]:min-h-[1.75rem] tw:[&_.button-surface\_\_content]:px-app-xs tw:[&_.button-surface\_\_content]:!py-0 tw:[&_.button-surface\_\_content_.icon]:!animate-none tw:[&_.button-surface\_\_content_.icon]:![transform:none] tw:[&_.button-surface\_\_content_.icon]:![transition:none] tw:[&_.button-surface\_\_content:hover]:!min-h-[1.75rem] tw:[&_.button-surface\_\_content:hover]:!rounded-[inherit] tw:[&_.button-surface\_\_content:hover]:!bg-transparent tw:[&_.button-surface\_\_content:hover]:!px-app-xs tw:[&_.button-surface\_\_content:hover]:!py-0 tw:[&_.button-surface\_\_content:active]:!min-h-[1.75rem] tw:[&_.button-surface\_\_content:active]:!rounded-[inherit] tw:[&_.button-surface\_\_content:active]:!bg-transparent tw:[&_.button-surface\_\_content:active]:!px-app-xs tw:[&_.button-surface\_\_content:active]:!py-0 tw:[&_.button-surface\_\_content:hover_.icon]:!stroke-current tw:[&_.button-surface\_\_content:hover_.icon]:![transform:none] tw:[&_.button-surface\_\_content:active_.icon]:!stroke-current tw:[&_.button-surface\_\_content:active_.icon]:![transform:none] tw:[&_.button:hover]:bg-[rgba(0,0,0,0.16)] tw:[&_.button:focus-visible]:bg-[rgba(0,0,0,0.16)] tw:[&_.button:hover_.button-surface\_\_label]:!text-inherit tw:[&_.button:focus-visible_.button-surface\_\_label]:!text-inherit`,
  close: 'snack-bar__close tw:ml-app-m tw:text-app-primary-contrast',
  message: String.raw`snack-bar__message tw:flex tw:flex-row tw:items-center tw:text-app-body tw:[&_.credit-amount]:text-inherit tw:[&_:is(.icon--CheckCircle,.icon--AlertCircle)]:mr-app-m tw:[&_:is(.icon--CheckCircle,.icon--AlertCircle)]:min-w-[1rem]`,
  messageText: 'snack-bar__messageText tw:min-w-0 tw:overflow-hidden tw:text-ellipsis',
  messageTextSub: 'snack-bar__messageText--sub tw:text-app-small tw:opacity-80',
} as const;
