%%% @doc Tests for `lbry_channel_key:pem_to_jwk/1', the PEM-to-JWK codec the
%%% wallet migration needs. The fixtures are REAL secp256k1 channel keys: keys
%%% generated by coincurve (the library LBRY uses), packed into a genuine
%%% wallet-sync blob with the LBRY SDK's own crypto, then recovered. Each key's
%%% expected private scalar was captured at generation time, so these tests
%%% prove the imported wallet is byte-for-byte the user's original channel key.
%%%
%%% Offline: fixtures are embedded; no network, no LBRY runtime.
-module(hb_lbry_channel_key_test).
-include_lib("eunit/include/eunit.hrl").
-include("include/lbry_test_keys.hrl").

%% Three real LBRY channel keys (PEM) with their known private scalars (hex).
fixtures() ->
    ?LBRY_CHANNEL_KEYS.

%% @doc The private scalar inside a wallet parsed by `ar_wallet:from_json'.
scalar_of(Wallet) ->
    {{_KeyType, Priv, _Pub}, _PubKey} = Wallet,
    Priv.

%% @doc Each real channel PEM converts to a JWK `ar_wallet' parses, and the
%% parsed private scalar equals the key's known scalar -- the migrated wallet is
%% the same secp256k1 key, not a fresh one.
pem_to_jwk_preserves_private_scalar_test() ->
    lists:foreach(
        fun({Pem, ExpectedHex}) ->
            Jwk = lbry_channel_key:pem_to_jwk(Pem),
            Wallet = ar_wallet:from_json(Jwk),
            ?assertEqual(ExpectedHex, hb_util:bin(hex(scalar_of(Wallet))))
        end,
        fixtures()
    ).

%% @doc Conversion is deterministic: the same PEM yields the same wallet address
%% every time, so re-running a migration for an account is idempotent.
pem_to_jwk_is_deterministic_test() ->
    lists:foreach(
        fun({Pem, _}) ->
            A = ar_wallet:from_json(lbry_channel_key:pem_to_jwk(Pem)),
            B = ar_wallet:from_json(lbry_channel_key:pem_to_jwk(Pem)),
            ?assertEqual(ar_wallet:to_address(A), ar_wallet:to_address(B))
        end,
        fixtures()
    ).

%% @doc A migrated channel key can sign and the signature verifies -- the
%% imported identity is usable, not just structurally valid.
migrated_key_signs_and_verifies_test() ->
    lists:foreach(
        fun({Pem, _}) ->
            {Priv, Pub} = ar_wallet:from_json(lbry_channel_key:pem_to_jwk(Pem)),
            Data = <<"migrate this channel">>,
            Sig = ar_wallet:sign(Priv, Data),
            ?assert(ar_wallet:verify(Pub, Data, Sig))
        end,
        fixtures()
    ).

%% @doc Distinct channel keys migrate to distinct wallets -- no collision across
%% a batch of migrated accounts.
distinct_keys_migrate_to_distinct_wallets_test() ->
    Addresses =
        [
            ar_wallet:to_address(ar_wallet:from_json(lbry_channel_key:pem_to_jwk(Pem)))
            || {Pem, _} <- fixtures()
        ],
    ?assertEqual(length(Addresses), length(lists:usort(Addresses))).

%% @doc Pin the FULL JWK (not just the private scalar) for the first corpus key
%% to the exact field values the JS importer's cross-check also pins
%% (importer/fixture-erlang-corpus-vector.json). If either side's PEM->JWK ever
%% changes its public-point (x/y) or scalar (d) encoding, one of the two suites
%% goes red instead of both silently agreeing with a stale fixture -- closing the
%% drift gap where the JS test compares only against a captured vector.
pem_to_jwk_matches_shared_vector_test() ->
    [{Pem, _} | _] = fixtures(),
    Jwk = hb_json:decode(lbry_channel_key:pem_to_jwk(Pem)),
    ?assertEqual(<<"EC">>, hb_maps:get(<<"kty">>, Jwk, undefined, #{})),
    ?assertEqual(<<"secp256k1">>, hb_maps:get(<<"crv">>, Jwk, undefined, #{})),
    ?assertEqual(<<"3Z3aeC9cJsTB-IkTiJCuyFFtlT14QLv4D7gPmQwzqmo">>,
        hb_maps:get(<<"x">>, Jwk, undefined, #{})),
    ?assertEqual(<<"3iADF1Tzqyz9iWZa65oHz1EhHqK6tRjm_3I3mgjRqSk">>,
        hb_maps:get(<<"y">>, Jwk, undefined, #{})),
    ?assertEqual(<<"TR_rBa6-7FSfQGwoPYGp-43dVZJfzHfzf0wBO7M2vWE">>,
        hb_maps:get(<<"d">>, Jwk, undefined, #{})).

%% @doc A non-secp256k1 PEM is rejected rather than silently imported.
non_secp256k1_key_rejected_test() ->
    {ok, PrimePem} = generate_prime256v1_pem(),
    ?assertError(_, lbry_channel_key:pem_to_jwk(PrimePem)).

hex(Bin) ->
    << <<(nibble(N))>> || <<N:4>> <= Bin >>.

nibble(N) when N < 10 -> $0 + N;
nibble(N) -> $a + N - 10.

%% Generate a PEM on the WRONG curve (prime256v1/P-256), to prove the converter
%% refuses a key that is not a secp256k1 channel key.
generate_prime256v1_pem() ->
    Key = public_key:generate_key({namedCurve, {1, 2, 840, 10045, 3, 1, 7}}),
    Der = public_key:der_encode('ECPrivateKey', Key),
    Pem = public_key:pem_encode([{'ECPrivateKey', Der, not_encrypted}]),
    {ok, Pem}.
