export const CHANNEL_COVER_CLASSES = {
  custom: String.raw`tw:absolute tw:z-0 tw:h-[284px] tw:min-h-[var(--cover-photo-height)] tw:w-full tw:self-start tw:object-cover tw:[border-bottom:none] tw:xlarge:h-[390px] tw:upto-small:h-[var(--cover-photo-height-small)] tw:upto-small:min-h-[var(--cover-photo-height-small)]`,
  headerContent: String.raw`channel-header-content tw:relative tw:mx-auto tw:h-full tw:w-[calc(100%-2*var(--spacing-l))] tw:max-w-[var(--page-max-width)] tw:[&_.menu\_\_button]:rounded-app tw:[&_.menu\_\_button]:bg-[rgba(var(--color-background-base),0.9)] tw:[&_.menu\_\_button]:p-[10px] tw:upto-small:w-full tw:upto-small:[&_.menu\_\_button]:w-[var(--height-button)] tw:upto-small:[&_.menu\_\_button]:self-end`,
  primaryInfo: String.raw`channel__primary-info tw:absolute tw:bottom-0 tw:z-[5] tw:mt-app-xl tw:box-border tw:w-full tw:min-w-0 tw:pb-app-m tw:pl-[12rem] tw:text-white tw:[&_.channel\_\_title_.comment\_\_badge]:ml-app-s tw:upto-small:mt-0 tw:upto-small:mb-0 tw:upto-small:pb-app-s tw:upto-small:pl-[calc((100%-(100%-3*var(--spacing-l))-2rem)/2+5rem)] tw:upto-small:[&_.channel\_\_title]:pt-0 tw:upto-small:[&_.channel\_\_title]:[font-size:x-large]`,
  quickActions: String.raw`channel__quick-actions tw:absolute tw:top-0 tw:right-0 tw:z-[2] tw:mt-app-m tw:ml-app-m tw:flex tw:flex-row tw:flex-wrap tw:[font-size:var(--font-base)] tw:[&>.button]:bg-[rgba(var(--color-background-base),0.9)]! tw:[&>.button]:px-app-s tw:[&>.button]:py-0 tw:[&>.button:not(:last-child)]:mr-app-s tw:[&_:is(.button,.menu\_\_button):is(:hover,[aria-expanded='true'])]:bg-[rgba(var(--color-header-background-base),0.95)]! tw:[&_:is(.button,.menu\_\_button):is(:hover,[aria-expanded='true'])]:text-[var(--color-link)] tw:[&_:is(.button,.menu\_\_button):is(:hover,[aria-expanded='true'])_.icon]:stroke-[var(--color-link)] tw:[.channel-cover_&]:select-none tw:upto-small:[.channel-cover_&]:m-0 tw:upto-small:[.channel-cover_&]:p-app-xs`,
  root: String.raw`channel-cover tw:relative tw:h-[284px] tw:min-h-[var(--cover-photo-height)] tw:w-full tw:bg-[linear-gradient(to_right,#637ad2,#318794_80%)] tw:bg-fixed tw:bg-no-repeat tw:[background-position-x:var(--side-nav-width--micro)] tw:[background-position-y:var(--header-height)] tw:[background-size:100vw_auto] tw:[border-bottom:none] tw:after:absolute tw:after:right-0 tw:after:bottom-0 tw:after:left-0 tw:after:h-full tw:after:w-full tw:after:bg-[linear-gradient(0deg,#0d0d0d_0,transparent_65%)] tw:after:opacity-100 tw:after:content-[''] tw:[&_.menu\_\_button]:justify-center tw:[&_.menu\_\_button]:opacity-100 tw:[@media(width>1600px)]:[background-position-x:calc(50%_+_var(--side-nav-width--micro)/2)] tw:[@media(width>1600px)]:[background-size:calc(100%_-_var(--side-nav-width--micro))] tw:[@media(width>900px)_and_(max-width:1600px)]:[background-position-x:calc(50%_+_var(--side-nav-width--micro))] tw:[@media(width>900px)_and_(max-width:1600px)]:[background-size:auto_284px] tw:xlarge:h-[390px] tw:upto-small:mx-[calc(var(--spacing-xs)*-1)] tw:upto-small:mt-[-20px] tw:upto-small:h-[var(--cover-photo-height-small)] tw:upto-small:min-h-[var(--cover-photo-height-small)] tw:upto-small:w-[calc(100%+2*var(--spacing-xs))]! tw:upto-small:[background-position-x:50%] tw:upto-small:[background-position-y:var(--header-height-mobile)] tw:upto-small:[background-size:auto_var(--cover-photo-height-small)]`,
  title: String.raw`channel__title tw:mr-app-s tw:flex tw:overflow-hidden tw:text-ellipsis tw:[font-size:xx-large] tw:[font-weight:var(--font-weight-bold)] tw:[&_.button]:ml-app-xs tw:[&_.comment\_\_badge]:pr-0 tw:[&_.comment\_\_badge_svg]:size-[2.5rem] tw:upto-small:pt-app-xl`,
  waiting: 'tw:absolute tw:size-full tw:bg-[var(--color-gray-5)] tw:[&_p]:p-[var(--padding-m)]',
} as const;
