export const COMMENT_MENU_LIVE_CLASS = 'tw:px-0 tw:py-app-xxs';

const COMMENT_MENU_CONTEXT_CLASS = String.raw`tw:[.block-modal--values_&]:text-app-xsmall tw:[.block-modal--values_&]:italic tw:[.card\_\_main-actions_&]:text-[rgba(var(--color-text-base),0.7)] tw:[.card\_\_main-actions_&_.icon]:mb-[2px] tw:[.card\_\_main-actions_&_.icon]:size-[12px] tw:[[data-membership-tier-editor]_&]:mt-[calc(var(--spacing-s)*-1)] tw:[[data-membership-tier-editor]_&]:mb-app-s tw:upto-small:[.modal_.card\_\_main-actions_&]:text-app-small tw:[.section_&]:text-app-text tw:[.section\_\_header--actions_.section\_\_actions--no-margin_&]:text-app-text`;

export const COMMENT_MENU_CLASSES = {
  active: String.raw`tw:mt-app-xxs tw:mb-[calc(var(--spacing-xxs)*-1)] tw:flex tw:min-w-[13rem] tw:items-center tw:bg-[var(--color-header-button)] tw:px-app-xxs tw:py-app-xxxxs tw:text-app-xsmall tw:text-app-text tw:whitespace-pre-line tw:[&_.channel-thumbnail]:mr-app-xs tw:[&_.channel-thumbnail]:size-[1.8rem] tw:[&_[data-comment-menu-channel]]:mr-0 tw:[&_[data-comment-menu-channel]]:text-[rgba(var(--color-text-base),0.8)] tw:[&_[data-comment-menu-channel]_span]:mt-[-2px] tw:[&_[data-comment-menu-channel]_span]:block tw:[&_[data-comment-menu-channel]_span]:max-w-[150px] tw:[&_[data-comment-menu-channel]_span]:overflow-hidden tw:[&_[data-comment-menu-channel]_span]:text-ellipsis tw:[&_[data-comment-menu-channel]_span]:text-app-text tw:[&_[data-comment-menu-channel]_span]:whitespace-nowrap`,
  channel: `${String.raw`tw:mt-0 tw:mr-app-s tw:max-w-[10rem] tw:overflow-hidden tw:text-app-xsmall tw:text-app-text tw:[display:-webkit-box] tw:[line-clamp:2] tw:[word-break:break-all] tw:[-webkit-box-orient:vertical] tw:[-webkit-line-clamp:2]`} ${COMMENT_MENU_CONTEXT_CLASS}`,
  help: `${String.raw`tw:mt-[2px] tw:block tw:max-w-[15rem] tw:pl-[calc(16px+var(--spacing-s))] tw:text-app-xsmall tw:text-app-text tw:whitespace-pre-line tw:opacity-80 tw:[&_.icon]:align-top tw:[.menu\_\_item:is([data-selected],:hover,:focus-visible,.Mui-focusVisible)_&]:!text-app-text-subtitle`} ${COMMENT_MENU_CONTEXT_CLASS}`,
  title: `${String.raw`tw:mt-0 tw:block tw:[border-bottom:1px_solid_var(--color-border)] tw:bg-app-header tw:pt-app-xs tw:pr-app-xl tw:pb-app-xs tw:pl-app-xs tw:text-app-small tw:text-app-text tw:[&.no-border]:![border-bottom:unset] tw:[&:not(:first-child)]:mt-app-xs tw:[&:not(:last-child)]:mb-app-xs tw:[&_.icon]:mr-app-xs tw:[&_.icon]:mb-[-8px]`} ${COMMENT_MENU_CONTEXT_CLASS}`,
};
