export const COMMENT_STICKER_CLASS =
  'sticker__comment tw:mb-app-xxs tw:ml-0 tw:h-[6rem] tw:overflow-hidden tw:[&_img]:max-h-full tw:[&_img]:max-w-full tw:upto-small:h-[5rem]';

export const COMMENT_CLASSES = {
  actionsDisabled: 'tw:pointer-events-none tw:brightness-50 tw:[&_button]:!text-white',
  author: String.raw`comment__author tw:mr-app-xs tw:h-full tw:[&_.button-surface\_\_content_p]:max-w-[16rem] tw:[&_.button-surface\_\_content_p]:overflow-hidden tw:[&_.button-surface\_\_content_p]:text-ellipsis tw:[&_.button-surface\_\_content_p]:whitespace-nowrap`,
  authorCreator: String.raw`comment__author--creator tw:mt-app-s tw:mb-app-xxxs tw:h-[18px] tw:overflow-hidden tw:text-ellipsis tw:whitespace-nowrap tw:rounded-app tw:bg-[var(--color-button-toggle-bg-active)] tw:px-[3px] tw:py-0 tw:text-app-primary-contrast! tw:[&_:is(.button-surface\_\_content,.channel-name)]:text-app-primary-contrast tw:[&.button--uri-indicator]:text-app-primary-contrast tw:[&.comment\_\_action]:text-app-primary-contrast tw:[&[data-comment-time]]:text-app-primary-contrast tw:hover:text-app-primary-contrast!`,
  authorThumbnail: String.raw`tw:[&_:is(.ff-canvas,.freezeframe-img)]:size-full tw:[&_:is(.ff-canvas,.freezeframe-img)]:[border-radius:50%]`,
  bodyContainer: String.raw`tw:ml-app-xs tw:flex tw:min-w-0 tw:flex-1 tw:flex-col tw:small:ml-app-s tw:hover:[&_.menu\_\_button]:opacity-100 tw:[&_.menu\_\_button_.icon]:[transition:transform_0.2s] tw:[&_[aria-expanded='true'].menu\_\_button]:rounded-[50%] tw:[&_[aria-expanded='true'].menu\_\_button]:bg-[rgba(var(--color-header-button-base),0.9)] tw:[&_[aria-expanded='true'].menu\_\_button]:opacity-100 tw:[&_[aria-expanded='true'].menu\_\_button]:[outline:2px_solid_var(--color-header-background)] tw:[&_[aria-expanded='true'].menu\_\_button_.icon]:[transform:rotate(90deg)] tw:[&_[aria-expanded='true'].menu\_\_button_.icon]:stroke-app-primary`,
  content: String.raw`comment__content tw:flex tw:w-full tw:flex-col tw:overflow-hidden tw:rounded-app tw:hover:[&_.ff-canvas]:!opacity-0 tw:hover:[&_.ff-canvas]:![transition:opacity_1s] tw:hover:[&_.ff-image]:!opacity-100`,
  dead: String.raw`tw:flex tw:items-center tw:[&_.icon]:ml-app-s`,
  menu: String.raw`tw:self-end tw:leading-none tw:[.comment\_\_list_.comments_.comment_&]:mt-[2px] tw:[.comment\_\_list_.comments_.comment_&]:mr-[2px] tw:upto-small:[&_.menu\_\_button]:opacity-100 tw:active-fullscreen-side-panel:[&_.menu\_\_button]:opacity-100`,
  message: String.raw`tw:pr-app-xl tw:text-app-text tw:[word-break:break-word] tw:[&_ul_li]:ml-app-l tw:[&_ul_li]:list-disc tw:[&_ul_li_p]:inline-block tw:[&_ul_li_ul_li]:ml-app-l tw:[&_ul_li_ul_li]:list-[circle] tw:[&_p+p]:mt-app-xxs tw:[&_.markdown-preview_ul]:mt-app-s tw:[&_.channel-name]:text-app-primary tw:[&_.channel-name_p]:text-app-small tw:[&_.channel-name:hover]:text-[var(--color-secondary)] tw:upto-small:pr-app-l tw:active-fullscreen-side-panel:pr-app-l`,
  metaInformation: String.raw`tw:flex tw:h-full tw:w-[calc(100%-var(--spacing-m)-var(--spacing-s))] tw:items-center tw:justify-start tw:pt-px tw:[&_.channel-name]:text-[var(--color-link)] tw:[&_.channel-name:hover]:text-[rgba(var(--color-secondary-dynamic),1)] tw:[&_.icon]:text-[var(--color-text)] tw:[&_.comment\_\_author]:text-app-primary tw:[&_.comment\_\_author--creator]:my-0 tw:[&_.comment\_\_author--creator_.channel-name]:text-app-primary-contrast tw:[&_.comment\_\_author--creator:hover_.channel-name]:text-app-primary-contrast tw:[&_.comment\_\_badge_svg]:size-[1.4rem] tw:[&_.credit-amount]:rounded-app tw:[&_.credit-amount]:bg-app-primary tw:[&_.credit-amount]:px-[4px] tw:[&_.credit-amount]:py-[3px] tw:[&_.credit-amount]:text-app-small tw:[&_.credit-amount]:font-bold tw:[&_.credit-amount]:text-white tw:[&_.comment\_\_pin]:mt-[-1px] tw:[&_.comment\_\_pin]:ml-0 tw:[&_.comment\_\_pin]:rounded-[10px_var(--border-radius)_var(--border-radius)_10px] tw:[&_.comment\_\_pin]:border-2 tw:[&_.comment\_\_pin]:border-app-border tw:[&_.comment\_\_pin]:bg-app-header tw:[&_.comment\_\_pin]:pt-0 tw:[&_.comment\_\_pin]:pr-[3px] tw:[&_.comment\_\_pin]:pb-0 tw:[&_.comment\_\_pin]:pl-[2px] tw:[&_.comment\_\_pin]:font-bold tw:[&_.comment\_\_pin_svg]:mr-app-xxs tw:[&_.comment\_\_pin_svg]:mb-[-3px] tw:[&_.comment\_\_pin_svg]:rounded-[50%] tw:[&_.comment\_\_pin_svg]:bg-app-border tw:[&_.comment\_\_pin_svg]:p-px tw:[&_.comment\_\_pin_svg]:pl-[2px] tw:upto-small:[&_.comment\_\_pin]:min-w-[22px] tw:upto-small:[&_.comment\_\_pin]:max-w-[22px] tw:upto-small:[&_.comment\_\_pin]:rounded-[50%] tw:active-fullscreen-side-panel:[&_.comment\_\_pin]:min-w-[22px] tw:active-fullscreen-side-panel:[&_.comment\_\_pin]:max-w-[22px] tw:active-fullscreen-side-panel:[&_.comment\_\_pin]:rounded-[50%] tw:[:is(.main--file-page,.main--livestream)_.file-page\_\_secondary-content_&_.date\_time]:!text-app-xsmall tw:[:is(.main--file-page,.main--livestream)_.file-page\_\_secondary-content_&_.date\_time]:text-[rgba(var(--color-text-base),0.6)] tw:[:is(.main--file-page,.main--livestream)_.file-page\_\_secondary-content_&_.date\_time:hover]:text-app-text`,
  reply: 'tw:m-0 tw:[&:not(:first-child)]:mt-app-m',
  thumbnailWrapper: 'tw:grid tw:grid-rows-[auto_1fr] tw:justify-items-stretch',
  threadline: String.raw`tw:left-1/2 tw:h-auto tw:rounded-none tw:border-l tw:border-l-[var(--color-comment-threadline)] tw:!bg-transparent tw:hover:border-l-4 tw:hover:border-l-[var(--color-comment-threadline)] tw:hover:!bg-transparent tw:hover:pr-[calc(var(--spacing-m)-3px)] tw:upto-small:hover:left-[calc(50%-3px)] tw:active-fullscreen-side-panel:hover:left-[calc(50%-3px)]`,
  time: String.raw`tw:mr-app-xs tw:h-full tw:whitespace-nowrap tw:opacity-60 tw:focus:bg-[var(--color-link-focus-bg)] tw:[.markdown-preview_&]:whitespace-normal`,
  topLevel: 'tw:[&:not(:first-child)]:mt-app-l',
} as const;
