export const NAG_CLASSES = {
  root: String.raw`nag tw:fixed tw:bottom-0 tw:left-0 tw:z-[997] tw:w-full tw:bg-[var(--color-nag)] tw:p-app-s tw:text-center tw:text-[var(--color-white)] tw:[font-weight:var(--font-weight-bold)] tw:[&_:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:text-[var(--color-white)] tw:[&_:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:[font-weight:var(--font-weight-bold)] tw:[&_:is(.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:underline tw:[&_.markdown-preview_a]:text-[var(--color-white)] tw:[&_.markdown-preview_a]:[font-weight:var(--font-weight-bold)] tw:[&_.markdown-preview_a]:underline tw:[.markdown-preview_&_a]:text-[var(--color-white)] tw:[.markdown-preview_&_a]:[font-weight:var(--font-weight-bold)] tw:[.markdown-preview_&_a]:underline tw:upto-small:text-left`,
  inline: String.raw`nag--inline tw:!absolute tw:!top-0 tw:!bottom-auto tw:!z-[1] tw:rounded-t-app tw:rounded-b-none tw:[[data-embed-inline-button]_&]:!top-[unset] tw:[[data-loading-screen]_&]:!top-[unset] tw:[.content\_\_autoplay-countdown_&]:!top-[unset]`,
  relative: 'nag--relative tw:!relative',
  helpful: String.raw`nag--helpful tw:mt-app-s tw:z-[998] tw:!bg-app-primary tw:!text-[var(--color-white)] tw:[[data-embed-inline-button]_&]:!bottom-0 tw:[[data-embed-inline-button]_&]:!rounded-none tw:[[data-embed-inline-button]_&_.button]:!inline-block tw:[[data-loading-screen]_&]:!bottom-0 tw:[[data-loading-screen]_&]:!rounded-none tw:[[data-loading-screen]_&_.button]:!inline-block tw:[.content\_\_autoplay-countdown_&]:!bottom-0 tw:[.content\_\_autoplay-countdown_&]:!rounded-none tw:[.content\_\_autoplay-countdown_&_.button]:!inline-block`,
  error: String.raw`nag--error tw:!right-app-s tw:!bottom-app-s tw:!left-app-s tw:!z-[99999999999] tw:box-border tw:w-[unset] tw:rounded-app tw:!bg-[rgba(0,0,0,0.9)] tw:text-app-text-error tw:[-webkit-backdrop-filter:blur(4px)] tw:[backdrop-filter:blur(4px)] tw:[.main\_\_sign-in_&]:!top-app-s tw:[.main\_\_sign-in_&]:!bottom-[unset] tw:[.main\_\_sign-in_&]:!left-0 tw:[.main\_\_sign-in_&]:!border-2 tw:[.main\_\_sign-in_&]:!border-solid tw:[.main\_\_sign-in_&]:!border-[red] tw:[.main\_\_sign-in_&]:!bg-[rgba(255,0,0,0.1)] tw:[.main\_\_sign-up_&]:!top-app-s tw:[.main\_\_sign-up_&]:!bottom-[unset] tw:[.main\_\_sign-up_&]:!left-0 tw:[.main\_\_sign-up_&]:!border-2 tw:[.main\_\_sign-up_&]:!border-solid tw:[.main\_\_sign-up_&]:!border-[red] tw:[.main\_\_sign-up_&]:!bg-[rgba(255,0,0,0.1)]`,
  message: String.raw`nag__message tw:inline tw:upto-small:after:block tw:upto-small:after:content-['']`,
  button: String.raw`nag__button tw:mx-app-s tw:rounded-app tw:border tw:border-solid tw:border-[var(--color-white)] tw:p-app-xxs tw:text-[var(--color-white)] tw:[font-weight:var(--font-weight-bold)] tw:leading-none tw:hover:bg-[var(--color-white)] tw:hover:text-[var(--color-nag)] tw:upto-small:mt-app-s tw:upto-small:ml-0`,
  buttonHelpful: 'nag__button--helpful tw:hover:!text-app-primary',
  buttonError:
    'nag__button--error tw:!border-app-text-error tw:!text-app-text-error tw:hover:!bg-app-text-error tw:hover:!text-[var(--color-white)]',
  close: String.raw`nag__close tw:!absolute tw:top-app-xs tw:right-app-m tw:!ml-auto tw:!border-none tw:[&_svg]:[stroke-width:4px] tw:upto-small:!top-0 tw:upto-small:!right-0`,
} as const;

export const CARD_FIXED_BOTTOM_WITH_NAG_CLASS = String.raw`tw:[body:has(.nag)_&]:bottom-[3rem]`;
