export const EMBED_REACTIONS_OVERLAY_CLASS = String.raw`embed-reactions-overlay tw:pointer-events-auto tw:absolute tw:top-1/2 tw:right-2 tw:z-[5] tw:flex tw:flex-col tw:gap-[0.075rem] tw:rounded-[9999px] tw:bg-[rgba(0,0,0,0.3)] tw:p-[0.25rem] tw:[transform:translateY(-50%)] tw:[&_.ratio-wrapper]:m-0 tw:[&_.ratio-wrapper]:flex tw:[&_.ratio-wrapper]:w-auto tw:[&_.ratio-wrapper]:min-w-[unset] tw:[&_.ratio-wrapper]:max-w-[unset] tw:[&_.ratio-wrapper]:flex-col tw:[&_.ratio-wrapper]:gap-[0.075rem] tw:[&_:is(.reaction-button-surface--like,.reaction-button-surface--dislike)_.button-surface\_\_label_:is(.counter-inline,.reaction-count-placeholder)]:hidden`;

const RECOMMENDATION_OVERLAY_CONTEXT_CLASSES = String.raw`tw:[[data-content-viewer-theater]_&]:px-[24%] tw:[[data-content-viewer-theater]_&]:pt-[4%] tw:[[data-content-viewer-theater]_&]:pb-[6%] tw:portrait:[[data-content-viewer-theater]_&]:!px-[10%] tw:portrait:[[data-content-viewer-theater]_&]:!pt-[5%] tw:portrait:[[data-content-viewer-theater]_&]:!pb-[7%] tw:[[data-floating-player]_&]:px-[20%] tw:[[data-floating-player]_&]:pt-[6%] tw:[[data-floating-player]_&]:pb-[14%] tw:[[data-content-viewer-mobile]_&]:rounded-none tw:[[data-content-viewer-mobile][data-floating-player]_&]:hidden`;

const RECOMMENDATION_GRID_TILE_CLASSES = String.raw`tw:[&_.claim-preview--tile]:m-0 tw:[&_.claim-preview--tile]:size-full tw:[&_.claim-preview--tile]:[animation:grow_0.6s_forwards] tw:[&_.claim-preview--tile_[data-claim-tile-header]]:absolute tw:[&_.claim-preview--tile_[data-claim-tile-header]]:top-0 tw:[&_.claim-preview--tile_[data-claim-tile-header]]:hidden tw:[&_.claim-preview--tile_[data-claim-tile-header]]:w-full tw:[&_.claim-preview--tile_[data-claim-tile-header]]:px-app-s tw:[&_.claim-preview--tile_[data-claim-tile-header]]:pt-0 tw:[&_.claim-preview--tile_[data-claim-tile-header]]:pb-app-m tw:[&_.claim-preview--tile_[data-claim-tile-header]]:[background:linear-gradient(180deg,rgba(13,13,13,0.9)_50%,rgba(13,13,13,0)_100%)] tw:[&_.claim-preview--tile_:is(.claim-preview\_\_hover-actions,.menu\_\_button)]:hidden tw:[&_.claim-preview--tile_.claim-tile\_\_info]:absolute tw:[&_.claim-preview--tile_.claim-tile\_\_info]:bottom-0 tw:[&_.claim-preview--tile_.claim-tile\_\_info]:hidden tw:[&_.claim-preview--tile_.claim-tile\_\_info]:w-full tw:[&_.claim-preview--tile_.claim-tile\_\_info]:px-app-s tw:[&_.claim-preview--tile_.claim-tile\_\_info]:py-app-m tw:[&_.claim-preview--tile_.claim-tile\_\_info]:[background:linear-gradient(0deg,rgba(13,13,13,0.9)_50%,rgba(13,13,13,0)_100%)] tw:[&_.claim-preview--tile_[data-claim-preview-file-property-overlay]]:m-app-xxs tw:[&_.claim-preview--tile_[data-claim-preview-file-property-overlay]]:hidden`;

const RECOMMENDATION_GRID_HOVER_CLASSES = String.raw`tw:[&_.claim-preview--tile:hover_.claim-tile\_\_info]:flex tw:[&_.claim-preview--tile:hover_.claim-tile\_\_info_:is(.channel-name,.date\_time)]:text-white tw:[&_.claim-preview--tile:hover_[data-claim-tile-header]]:flex tw:[&_.claim-preview--tile:hover_[data-claim-tile-header]_.claim-preview\_\_title]:text-white tw:[&_.claim-preview--tile:hover_[data-claim-tile-header]_.placeholder_.claim-preview\_\_title\_b]:text-white tw:[.placeholder_&_.claim-preview--tile:hover_[data-claim-tile-header]_.claim-preview\_\_title\_b]:text-white tw:[&_.claim-preview--tile:hover_[data-claim-preview-file-property-overlay]]:block tw:[&_.claim-preview--tile:hover_.media\_\_thumb]:[box-shadow:unset]`;

const RECOMMENDATION_GRID_FLOATING_CLASSES = String.raw`tw:[[data-floating-player]_&_div]:[transition:background-size_0.2s] tw:[[data-floating-player]_&_.claim-preview--tile:hover_:is(.claim-tile\_\_info,[data-claim-tile-header],[data-claim-preview-file-property-overlay])]:hidden`;

export const RECOMMENDATION_OVERLAY_CLASSES = {
  wrapper: String.raw`tw:pointer-events-none tw:absolute tw:inset-0 tw:z-[1] tw:rounded-app tw:px-[10%] tw:pt-[3%] tw:pb-[80px] tw:[animation:blendin_1s_forwards] tw:[&_*]:pointer-events-auto tw:upto-small:px-[18%] tw:upto-small:pt-[4%] tw:upto-small:pb-[90px] ${RECOMMENDATION_OVERLAY_CONTEXT_CLASSES}`,
  grid: String.raw`tw:grid tw:size-full tw:grid-cols-3 tw:gap-app-xxs ${RECOMMENDATION_GRID_TILE_CLASSES} ${RECOMMENDATION_GRID_HOVER_CLASSES} ${RECOMMENDATION_GRID_FLOATING_CLASSES}`,
  item: String.raw`tw:[[data-floating-player]_&:hover]:!cursor-pointer tw:[[data-floating-player]_&:hover_.media\_\_thumb]:[background-size:108%]`,
  replayItem: String.raw`tw:[[data-content-viewer-mobile]_&]:bg-[length:40%] tw:[[data-content-viewer-mobile]_&]:bg-center tw:[[data-content-viewer-mobile]_&]:bg-no-repeat tw:[[data-content-viewer-mobile]_&]:[background-image:var(--recommendation-replay-background-image)] tw:[[data-content-viewer-mobile]_&_.claim-preview--tile]:pointer-events-none tw:[[data-content-viewer-mobile]_&_.claim-preview--tile]:opacity-0`,
} as const;
