import { SECTION_CLASSES } from '../common/section-classes.ts';

export const CLAIM_SEARCH_WRAPPER_WRAP_CLASS = String.raw`claim-search__wrapper--wrap tw:flex tw:flex-wrap tw:gap-app-xs tw:first-of-type:flex-1 tw:first-of-type:[&_.claim-search\_\_menu-group]:w-full tw:upto-small:[&_.wunderbar--inline]:mt-0 tw:upto-small:[&_.wunderbar--inline]:mb-app-xxs tw:upto-small:last-of-type:mt-app-s`;

export const CLAIM_SEARCH_MENU_GROUP_CLASS = String.raw`claim-search__menu-group tw:flex tw:flex-nowrap tw:upto-medium:[&_.button-toggle-surface]:py-0 tw:upto-medium:[&_.button-toggle-surface]:pr-app-s tw:upto-medium:[&_.button-toggle-surface]:pl-app-xs`;

export const CLAIM_SEARCH_MENU_SUBGROUP_CLASS = String.raw`claim-search__menu-subgroup tw:flex tw:flex-row tw:[&_.claim-search\_\_dropdown]:mt-0 tw:[&_.claim-search\_\_dropdown]:[font-size:var(--font-base)] tw:[&_.claim-search\_\_dropdown:first-of-type]:ml-app-xs tw:[&:nth-of-type(2)]:items-center tw:[&:nth-of-type(2)]:justify-center tw:[&:nth-of-type(2)]:gap-app-xs tw:upto-medium:[&:nth-of-type(2)]:justify-end`;

export const CLAIM_SEARCH_DROPDOWN_CLASS = 'claim-search__dropdown tw:pl-0 tw:upto-small:pr-0';

const CLAIM_SEARCH_TOP_CHANNEL_CONTEXT_CLASS = [
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group]:box-border tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group]:mb-0`,
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(1)]:w-full tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(1)]:basis-full tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(1)]:mb-app-xxs`,
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(1)_button]:flex-1 tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(1)_button_.button-surface\_\_content]:justify-center`,
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_:is(.claim-search\_\_menu-group:nth-of-type(2),.claim-search\_\_menu-group:nth-of-type(3))]:basis-1/2`,
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(3)_button]:ml-auto`,
  String.raw`tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(3)_button:after]:bottom-[-7px] tw:upto-small:[.channelPage-wrapper_.section\_\_header--actions_:is(.section\_\_actions,.section\_\_actions--no-margin,.section\_\_actions--between,.section\_\_actions--centered)_&_.claim-search\_\_menu-group:nth-of-type(3)_button:after]:[border-bottom:7px_solid_var(--color-header-button)]`,
].join(' ');

export const CLAIM_LIST_HEADER_CLASSES = {
  wrapper: 'claim-search__wrapper clh__wrapper tw:w-full',
  header: 'claim-search__header tw:flex tw:items-stretch',
  top: String.raw`claim-search__top tw:flex tw:flex-grow tw:flex-wrap tw:justify-between tw:gap-app-xs tw:[&_.claim-search\_\_menu-group:last-of-type]:mr-[unset] tw:small:justify-start tw:upto-medium:flex-nowrap tw:upto-small:flex-wrap tw:upto-small:justify-start ${CLAIM_SEARCH_TOP_CHANNEL_CONTEXT_CLASS}`,
  menuGroup: `${CLAIM_SEARCH_MENU_GROUP_CLASS} tw:upto-small:mt-app-xs`,
  menuGroupStretch: 'stretch tw:upto-medium:w-full tw:upto-small:min-w-0 tw:upto-small:flex-[1_0_100%]',
  meta: `${SECTION_CLASSES.actionsNoMargin} tw:ml-auto tw:[justify-content:end] tw:upto-small:top-0 tw:upto-small:right-0 tw:upto-small:!mt-app-s`,
  hideAnonymous: String.raw`hide-anonymous-checkbox tw:flex tw:h-[var(--height-input)] tw:items-center tw:justify-center tw:rounded-app tw:bg-[var(--color-header-button)] tw:px-app-s tw:[&_:is(label,.confirm\_\_label)]:mb-[-4px] tw:[&_:is(label,.confirm\_\_label)]:pl-[calc(var(--height-checkbox)+var(--spacing-s))] tw:[&_:is(label,.confirm\_\_label)]:[font-size:var(--font-base)] tw:[&_:is(label,.confirm\_\_label)]:font-bold tw:[&_:is(label,.confirm\_\_label)::before]:mt-[-2px] tw:[&_:is(label,.confirm\_\_label)::before]:bg-app-background tw:[&_:is(label,.confirm\_\_label)::after]:mt-[-2px] tw:[&_:is(label,.confirm\_\_label)::after]:[background:none] tw:upto-small:[&_:is(label,.confirm\_\_label)]:mb-0 tw:upto-small:[&_:is(label,.confirm\_\_label)]:text-app-xxsmall tw:upto-small:[&_:is(label,.confirm\_\_label)::before]:mt-[10px] tw:upto-small:[&_:is(label,.confirm\_\_label)::after]:mt-[4px]`,
  filtersWrapper: 'claim-search__filters-wrapper tw:max-h-0 tw:overflow-hidden tw:[transition:max-height_0.3s]',
  filtersWrapperExpanded: String.raw`claim-search__filters-wrapper-expanded tw:max-h-[300px] tw:[&_.filer-checkbox-wrapper]:flex tw:[&_.filer-checkbox-wrapper]:flex-col tw:[&_.filer-checkbox-wrapper]:rounded-app tw:[&_.filer-checkbox-wrapper]:pt-app-xs tw:[&_.filer-checkbox-wrapper]:pl-app-s tw:[&_.filer-checkbox-wrapper_div_.checkbox]:mt-app-xs tw:[&_.filer-checkbox-wrapper_div:last-of-type_.checkbox]:mb-app-xs tw:upto-small:max-h-[700px]`,
  filters: String.raw`claim-search__filters tw:mt-app-s tw:w-full tw:rounded-app tw:bg-[var(--color-header-button)] tw:pt-app-s tw:pr-app-m tw:pb-app-m tw:pl-app-m tw:[&_.claim-search\_\_menus]:m-0 tw:[&_.claim-search\_\_menus]:gap-app-m tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container]:flex-[1_1_0] tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container]:pr-0 tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container_:is(label,.confirm\_\_label)]:mt-app-s tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container_:is(label,.confirm\_\_label)]:mb-[0.1rem] tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container_:is(label,.confirm\_\_label)]:[font-size:var(--font-base)] tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container_:is(label,.confirm\_\_label)]:font-bold tw:[&_.claim-search\_\_menus_.claim-search\_\_input-container:last-child_.claim-search\_\_dropdown]:pr-0 tw:[&_:is(select,.filer-checkbox-wrapper,input[type='text'],input[type='number'])]:bg-app-background tw:[&_.filer-checkbox-wrapper]:pt-app-xxxs tw:[&_.filer-checkbox-wrapper_:is(label,.confirm\_\_label)]:!mt-0 tw:upto-small:mb-app-s`,
  menus:
    'claim-search__menus tw:mb-app-m tw:flex tw:flex-col tw:flex-wrap tw:items-start tw:justify-start tw:text-app-text-subtitle tw:small:flex-row tw:upto-small:p-[unset]',
  inputContainer:
    'claim-search__input-container tw:flex tw:w-full tw:flex-col tw:pl-0 tw:text-app-body tw:upto-small:pr-0',
  dropdown: CLAIM_SEARCH_DROPDOWN_CLASS,
  durationInputs: String.raw`claim-search__duration-inputs-container tw:flex tw:content-start tw:[&_input]:mr-app-m tw:upto-small:w-full tw:upto-small:[&_.claim-search\_\_input-container]:mt-0 tw:upto-small:[&_.claim-search\_\_input-container_:is(label,.confirm\_\_label)]:!mt-app-m tw:upto-small:[&_.claim-search\_\_input-container_input]:w-full tw:upto-small:[&_.claim-search\_\_input-container:first-of-type_input]:w-[calc(100%-var(--spacing-m))]`,
  filterButton: 'claim-search__filter-button tw:flex tw:items-center tw:justify-center tw:p-0',
  additionalFiltersNotice:
    'additional-filters__notice tw:mt-app-xs tw:block tw:text-app-xsmall tw:text-app-text-subtitle',
  toggleBottomArrow: String.raw`button-toggle--bottom-arrow tw:[--button-toggle-icon-stroke:var(--color-primary-contrast)] tw:after:absolute tw:after:bottom-[-11px] tw:after:left-[calc(50%-10px)] tw:after:size-0 tw:after:[border-right:10px_solid_transparent] tw:after:[border-bottom:11px_solid_var(--color-header-button)] tw:after:[border-left:10px_solid_transparent] tw:after:content-[''] tw:[&.button-toggle-surface--active_.button-surface\_\_content_.icon]:![stroke:var(--color-primary-contrast)] tw:hover:cursor-pointer tw:hover:[--color-button-toggle-bg-active:var(--color-primary)]`,
  toggleCustom: String.raw`button-toggle--custom tw:[--color-button-toggle-text-active:var(--color-primary)] tw:!text-app-primary tw:[&_.button-surface\_\_content_.icon]:!stroke-[var(--color-primary)] tw:[&_svg]:opacity-100 tw:hover:[&_.icon]:!stroke-[var(--color-primary-contrast)]`,
} as const;

export const CLAIM_LIST_HEADER_TAG_CLASSES = {
  root: String.raw`clh-tag-search tw:[&_.button-toggle-surface]:rounded-app tw:[&_.button-toggle-surface--active]:rounded-[var(--border-radius)_0_0_var(--border-radius)]`,
  standalone: 'clh-tag-search--standalone tw:ml-app-xs tw:w-full tw:upto-small:ml-0 tw:upto-small:min-w-0',
  inputGroup: String.raw`clh-tag-search__input_group tw:relative tw:flex tw:w-full tw:[&_:is(fieldset-section,.fieldset-section)]:w-full tw:[&_input::placeholder]:text-app-body tw:[&_.icon]:absolute tw:[&_.icon]:top-[calc(50%-8px)] tw:[&_.icon]:left-app-s`,
  input: 'clh-tag-search__input tw:w-full tw:pr-[30px] tw:pl-[36px]',
  clear: String.raw`clh-tag-search__clear tw:absolute tw:right-app-xxxs tw:bg-[unset] tw:[&_.icon]:[transform:rotate(0deg)] tw:[&_.icon]:[transition:transform_0.2s] tw:hover:bg-[unset] tw:hover:[&_.icon]:stroke-[var(--color-primary)] tw:hover:[&_.icon]:[transform:rotate(90deg)]`,
} as const;
