export const PLAYLIST_PICKER_CLASSES = {
  modal: String.raw`playlist-picker-modal tw:relative tw:flex tw:h-auto tw:!w-[38rem] tw:!min-w-0 tw:!max-w-[calc(100vw-2rem)] tw:!max-h-[calc(100dvh-2rem)] tw:overflow-hidden tw:!rounded-app tw:!p-0`,
  panel: String.raw`playlist-picker tw:flex tw:min-h-0 tw:w-full tw:flex-col`,
  header: String.raw`playlist-picker__header tw:flex tw:shrink-0 tw:items-center tw:pr-[3.5rem] tw:pl-app-m tw:pt-app-m tw:pb-app-s`,
  title: String.raw`playlist-picker__title tw:min-w-0 tw:text-[1.5rem] tw:font-bold tw:leading-tight tw:text-app-text`,
  search: String.raw`playlist-picker__search tw:relative tw:mx-app-m tw:mb-app-xs tw:block tw:shrink-0`,
  searchIcon: String.raw`playlist-picker__search-icon tw:pointer-events-none tw:absolute tw:top-1/2 tw:left-app-m tw:size-5 tw:-translate-y-1/2 tw:text-app-text-subtitle`,
  searchInput: String.raw`playlist-picker__search-input tw:h-10 tw:w-full tw:rounded-app tw:border tw:border-transparent tw:bg-[var(--color-header-button)] tw:pr-app-m tw:pl-[3rem] tw:text-app-body tw:text-app-text tw:placeholder:text-app-text-subtitle tw:placeholder:opacity-100 tw:hover:border-app-border tw:focus-visible:border-app-primary tw:focus-visible:[box-shadow:none]`,
  list: String.raw`playlist-picker__list tw:m-0 tw:min-h-[7rem] tw:max-h-[min(48vh,22rem)] tw:list-none tw:overflow-y-auto tw:px-app-m tw:pb-app-xs`,
  empty: String.raw`playlist-picker__empty tw:flex tw:min-h-[7rem] tw:items-center tw:justify-center tw:px-app-m tw:text-center tw:text-app-body tw:text-app-text-subtitle`,
  loading: String.raw`playlist-picker__loading tw:flex tw:min-h-[18rem] tw:items-center tw:justify-center`,
  item: String.raw`playlist-picker__item tw:m-0 tw:list-none`,
  row: String.raw`playlist-picker__row tw:grid tw:w-full tw:grid-cols-[4.5rem_minmax(0,1fr)_2.25rem] tw:items-center tw:gap-app-s tw:rounded-app tw:px-0 tw:py-app-xxs tw:text-left tw:text-app-text tw:transition-colors tw:duration-100 tw:hover:bg-[rgba(var(--color-header-button-base),0.35)] tw:focus-visible:bg-[rgba(var(--color-primary-dynamic),0.12)] tw:focus-visible:[box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset] tw:disabled:pointer-events-none tw:disabled:opacity-50 tw:upto-xsmall:grid-cols-[4.25rem_minmax(0,1fr)_2.25rem]`,
  rowSelected: String.raw`playlist-picker__row--selected tw:bg-[rgba(var(--color-primary-dynamic),0.08)]`,
  preview: String.raw`playlist-picker__preview tw:relative tw:grid tw:aspect-video tw:w-[4.5rem] tw:place-items-center tw:overflow-hidden tw:rounded-app-thumbnail tw:bg-[rgba(var(--color-header-button-base),0.35)] tw:upto-xsmall:w-[4.25rem]`,
  previewImage: String.raw`playlist-picker__preview-image tw:absolute tw:inset-0 tw:size-full tw:object-cover`,
  previewIcon: String.raw`playlist-picker__preview-icon tw:size-6 tw:text-app-text-subtitle`,
  copy: String.raw`playlist-picker__copy tw:flex tw:min-w-0 tw:flex-col tw:gap-0.5`,
  itemTitle: String.raw`playlist-picker__item-title tw:block tw:overflow-hidden tw:text-ellipsis tw:whitespace-nowrap tw:text-app-body tw:font-semibold tw:leading-snug tw:text-app-text`,
  metadata: String.raw`playlist-picker__metadata tw:flex tw:min-w-0 tw:items-center tw:gap-app-xxs tw:overflow-hidden tw:whitespace-nowrap tw:text-app-xsmall tw:leading-snug tw:text-app-text-subtitle`,
  privacy: String.raw`playlist-picker__privacy tw:flex tw:shrink-0 tw:items-center tw:gap-app-xxs`,
  privacyIcon: String.raw`playlist-picker__privacy-icon tw:size-3 tw:shrink-0 tw:stroke-[var(--color-text-subtitle)]`,
  itemCount: String.raw`playlist-picker__item-count tw:overflow-hidden tw:text-ellipsis tw:whitespace-nowrap`,
  indicator: String.raw`playlist-picker__indicator tw:grid tw:size-9 tw:place-items-center tw:justify-self-end tw:rounded-app tw:border tw:border-app-border tw:text-app-text-subtitle tw:transition-colors tw:duration-100 tw:[&_.icon]:size-5`,
  indicatorSelected: String.raw`playlist-picker__indicator--selected tw:border-app-primary tw:bg-app-primary tw:text-app-primary-contrast tw:[&_.icon]:stroke-[var(--color-primary-contrast)]`,
  footer: String.raw`playlist-picker__footer tw:shrink-0 tw:border-t tw:border-app-border tw:p-app-m`,
  newButton: String.raw`playlist-picker__new-button tw:flex tw:h-11 tw:w-full tw:items-center tw:justify-center tw:rounded-app tw:bg-[var(--color-header-button)] tw:px-app-m tw:font-semibold tw:text-app-text tw:transition-colors tw:duration-100 tw:hover:bg-[var(--color-border)] tw:focus-visible:bg-[rgba(var(--color-primary-dynamic),0.12)] tw:focus-visible:[box-shadow:0_0_0_var(--form-control-ring-width)_var(--color-primary)_inset] tw:[&_.button-surface\_\_content]:justify-center tw:[&_.button-surface\_\_label]:mt-0 tw:[&_.button-surface\_\_label]:text-app-text tw:[&_.icon]:stroke-[var(--color-text)]`,
  createForm: String.raw`playlist-picker__create-form tw:w-full tw:[&_fieldset-section]:gap-app-xs tw:[&_fieldset-section>div]:leading-none tw:[&_label]:!text-app-text tw:[&_input-submit]:w-full tw:[&_input-submit>input]:min-w-0 tw:[&_input-submit>input]:flex-1 tw:[&_input-submit>input]:!border tw:[&_input-submit>input]:!border-app-border tw:[&_input-submit>input]:!bg-[var(--color-header-button)] tw:[&_input-submit>input]:text-app-text tw:[&_input-submit>input]:placeholder:text-app-text-subtitle tw:[&_.button-toggle-surface]:!h-[var(--height-input)]`,
} as const;
