// Verification sweep: run the importer over a matrix of genuine LBRY
// wallet-sync payloads (fixtures/, generated by gen-sweep-fixtures.py) and
// assert each outcome. Success cases must recover the expected channel keys
// byte-for-byte; adversarial cases (wrong password, tampered, malformed) must
// be rejected, never silently yielding a wrong key. Run: node sweep.mjs
import { extractChannelKeys, channelPemToJwk } from './lbry-wallet-importer.mjs';
import { readFileSync } from 'node:fs';
import assert from 'node:assert';

const manifest = JSON.parse(
  readFileSync(new URL('./fixtures/manifest.json', import.meta.url), 'utf8'),
);

const scalarsOf = (pems) =>
  pems.map((pem) => Buffer.from(JSON.parse(channelPemToJwk(pem)).d, 'base64url').toString('hex')).sort();

let pass = 0;
for (const c of manifest.cases) {
  const blob = readFileSync(new URL(`./fixtures/${c.file}`, import.meta.url));
  const label = `${c.file} (pw=${JSON.stringify(c.password)})`;
  if (c.expectError) {
    assert.throws(() => extractChannelKeys(c.password, blob), `${label}: expected rejection`);
    console.log(`OK  reject   ${label}`);
  } else {
    const got = scalarsOf(extractChannelKeys(c.password, blob));
    const want = [...c.expectKeys].sort();
    assert.deepEqual(got, want, `${label}: recovered keys must match`);
    console.log(`OK  recover  ${label} -> ${got.length} key(s)`);
  }
  pass++;
}
console.log(`\nsweep: ${pass}/${manifest.cases.length} cases passed`);
