// Verification sweep: run the importer over a matrix of genuine LBRY
// wallet-sync payloads (fixtures/, generated by gen-sweep-fixtures.py) and
// assert each outcome. Success cases must recover the expected channel keys
// byte-for-byte; adversarial cases (wrong password, tampered, malformed) must
// be rejected, never silently yielding a wrong key. Run: node sweep.mjs
import { extractChannelKeys, channelPemToJwk } from './lbry-wallet-importer.mjs';
import { readFileSync } from 'node:fs';
import assert from 'node:assert';

const manifest = JSON.parse(
  readFileSync(new URL('./fixtures/manifest.json', import.meta.url), 'utf8'),
);

const scalarsOf = (pems) =>
  pems.map((pem) => Buffer.from(JSON.parse(channelPemToJwk(pem)).d, 'base64url').toString('hex')).sort();

let pass = 0;
for (const c of manifest.cases) {
  const blob = readFileSync(new URL(`./fixtures/${c.file}`, import.meta.url));
  const label = `${c.file} (pw=${JSON.stringify(c.password)})`;
  if (c.expectError) {
    // Assert it throws AND capture the reason, so a reject case can never pass
    // vacuously (a string 2nd arg to assert.throws is the message, not a
    // matcher). We also assert no key ever slips through on the failure path.
    let threw = null;
    try { extractChannelKeys(c.password, blob); }
    catch (e) { threw = e; }
    assert.ok(threw, `${label}: expected rejection, but it returned`);
    console.log(`OK  reject   ${label} -> ${threw.message.split('\n')[0].slice(0, 60)}`);
  } else {
    const got = scalarsOf(extractChannelKeys(c.password, blob));
    const want = [...c.expectKeys].sort();
    assert.deepEqual(got, want, `${label}: recovered keys must match`);
    console.log(`OK  recover  ${label} -> ${got.length} key(s)`);
  }
  pass++;
}
console.log(`\nsweep: ${pass}/${manifest.cases.length} cases passed`);
