const FULLSCREEN_RENDER_CHILD_CLASS = String.raw`tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!size-full tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!min-h-0 tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!max-w-none tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!max-h-none tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!m-0 tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!overflow-hidden tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!rounded-none tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!p-0 tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!relative tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:![aspect-ratio:unset] tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:![transform:none] tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!top-auto tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!right-auto tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!bottom-auto tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:!left-auto tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:![inset:auto]`;

export const PRIMARY_PLAYER_WRAPPER_STYLE_CLASS =
  'file-page__video-container tw:relative tw:flex tw:h-full tw:max-h-[var(--desktop-portrait-player-max-height)] tw:w-full tw:overflow-visible';

export const INLINE_PLAYER_WRAPPER_STYLE_CLASS =
  'inline-player__wrapper tw:aspect-video tw:!rounded-app tw:[&_.button-surface--play]:!inline-block';

export const FILE_RENDER_CLASSES = {
  base: String.raw`tw:size-full tw:z-[1] tw:overflow-hidden tw:upto-small:max-h-[var(--mobile-player-max-height)] tw:[[data-embed-wrapper]_&]:!rounded-none ${FULLSCREEN_RENDER_CHILD_CLASS}`,
  embed: String.raw`tw:fixed tw:!max-h-none tw:!rounded-app tw:[[data-claim-link]_&]:!relative tw:[&[data-file-render-video]]:aspect-video tw:[:is(.inline-player\_\_wrapper,[data-embed-wrapper])_&_.button-surface--play]:!hidden`,
  video: String.raw`tw:rounded-app tw:bg-black tw:after:pointer-events-none tw:after:absolute tw:after:inset-0 tw:after:z-[2] tw:after:bg-black tw:after:opacity-0 tw:after:content-[''] tw:after:[animation:fadeInFromBlack_2s_ease] tw:upto-small:rounded-none tw:[:is(.player-fullscreen-target:fullscreen,html.ios-fullscreen_.player-fullscreen-target)_&]:after:!hidden`,
} as const;

export const FILE_VIEWER_CLASSES = {
  base: String.raw`tw:size-full tw:[&_:is(iframe,webview,img)]:size-full tw:[&_:is(iframe,webview,img)]:max-h-[var(--inline-player-max-height)] tw:[&_:is(iframe,webview,img)]:object-contain tw:[&_video]:cursor-pointer tw:[[data-file-render-video]_&]:relative tw:[[data-file-render-embed]_&_:is(iframe,webview,img)]:max-h-none tw:[[data-embed-wrapper]_&]:!rounded-none tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!m-0 tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!h-full tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!w-auto tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!flex tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!flex-col tw:[[data-embed-wrapper]_&_.claim-preview--tile]:!justify-center tw:[[data-embed-wrapper]_&_.claim-preview--tile_.media\_\_thumb]:!rounded-none ${FULLSCREEN_RENDER_CHILD_CLASS}`,
  content: 'tw:size-full tw:max-w-[100vw] tw:overflow-auto',
  download: 'tw:cursor-pointer',
  document: String.raw`tw:[[data-embed-wrapper]_&]:text-app-text tw:[.file-page_.file-page\_\_md_&]:mt-app-l tw:[.file-page_.file-page\_\_md_&_.button]:inline tw:[.file-page_.file-page\_\_md_&_.button_.button-surface\_\_content]:inline tw:[.file-page_.file-page\_\_md_&_[data-claim-link]_.button]:block tw:[.file-page_.file-page\_\_md_&_[data-claim-link]_.button_.button-surface\_\_content]:block`,
  embeddedGradient:
    'tw:absolute tw:top-0 tw:right-0 tw:left-0 tw:z-[1] tw:h-[75px] tw:[background:linear-gradient(#000000,rgba(0,0,0,0)_70%)]',
  embeddedHeader: String.raw`tw:absolute tw:top-0 tw:z-[6] tw:grid tw:w-full tw:grid-cols-[minmax(5rem,calc(100%_-_7rem))_1fr] tw:overflow-x-hidden tw:overflow-y-hidden tw:text-ellipsis tw:whitespace-nowrap tw:rounded-t-app tw:p-app-xxs tw:text-app-large tw:opacity-100 tw:[&_.button]:[z-index:2] tw:[&_.button]:p-app-xxs tw:[&_.button]:text-[var(--color-white)] tw:[&_.button:hover]:text-[var(--color-white)] tw:[&_.button_.button-surface\_\_label]:whitespace-nowrap tw:[&_.credit-amount]:mr-app-m tw:[[data-file-render-video][data-file-render-embed]:hover_&]:!opacity-100 tw:[[data-embed-wrapper]_&]:!w-screen tw:[[data-embed-wrapper]_&]:!rounded-none tw:[.inline-player\_\_wrapper_&]:grid-cols-[minmax(0,1fr)_auto] tw:[.inline-player\_\_wrapper_&]:text-[0.875rem] tw:[.inline-player\_\_wrapper_&_.button]:p-app-xxxs`,
  embeddedEnded: 'file-viewer--ended-embed',
  embeddedEndedTitle: 'tw:max-w-full tw:[&_p]:text-[6vh] tw:[&_p]:whitespace-pre-wrap',
  embeddedInfo: 'tw:justify-self-end tw:[&>*:not(:last-child)]:mr-app-s',
  embeddedTitle: String.raw`tw:[z-index:2] tw:flex tw:items-center tw:pl-app-s tw:text-white tw:[[data-embed-inline-button]_&]:text-[0.875rem] tw:[[data-embed-inline-button]_&]:leading-[1.2] tw:[.inline-player\_\_wrapper_&]:min-w-0 tw:[.inline-player\_\_wrapper_&]:leading-[1.2] tw:[.markdown-preview_&]:block tw:[.markdown-preview_&_.button-surface\_\_label]:!inline-block tw:[.markdown-preview_&_.button-surface\_\_label]:!w-full`,
  iframe: 'tw:flex tw:[&_iframe]:!h-[calc(100vh-var(--header-height)-var(--spacing-m)*2)]',
  overlay: String.raw`tw:absolute tw:right-auto tw:left-auto tw:z-[2] tw:flex tw:size-full tw:flex-col tw:items-center tw:justify-center tw:bg-[rgba(0,0,0,0.9)] tw:p-app-l tw:text-app-body tw:text-[var(--color-white)] tw:[&_:is(.button--uri-indicator,[data-comment-time],.comment\_\_action,.button-surface--link,.tab,.footer\_\_link)]:text-[var(--color-white)] tw:[&_.markdown-preview_a]:text-[var(--color-white)] tw:[.markdown-preview_&_a]:text-[var(--color-white)] tw:upto-small:text-app-small`,
  overlayTitle:
    'tw:mb-app-m tw:text-center tw:text-app-large tw:upto-small:max-w-full tw:upto-small:overflow-hidden tw:upto-small:text-ellipsis tw:upto-small:whitespace-nowrap',
  overlaySecondary:
    'tw:mb-app-m tw:text-app-text-subtitle tw:upto-small:mb-0 tw:upto-small:max-w-full tw:upto-small:overflow-hidden tw:upto-small:text-ellipsis tw:upto-small:whitespace-nowrap',
  overlayLogo: String.raw`tw:text-[var(--color-white)] tw:font-bold tw:[&_.icon]:h-[30px] tw:[&_.icon]:[stroke-width:5px] tw:[[data-embed-inline-button]_&]:pl-0 tw:[[data-embed-inline-button]_&_:is(.icon,[data-embed-overlay-logo],svg)]:!h-[24px] tw:[[data-embed-inline-button]_&_:is(.icon,[data-embed-overlay-logo],svg)]:!w-auto tw:[[data-embed-inline-button]_&_:is(.icon,[data-embed-overlay-logo],svg)]:max-w-none tw:[.inline-player\_\_wrapper_&]:inline-flex tw:[.inline-player\_\_wrapper_&]:w-auto tw:[.inline-player\_\_wrapper_&]:items-center tw:[.inline-player\_\_wrapper_&_:is(.icon,[data-embed-overlay-logo],svg)]:block tw:[.inline-player\_\_wrapper_&_:is(.icon,[data-embed-overlay-logo],svg)]:!h-[24px] tw:[.inline-player\_\_wrapper_&_:is(.icon,[data-embed-overlay-logo],svg)]:!w-auto tw:[.inline-player\_\_wrapper_&_:is(.icon,[data-embed-overlay-logo],svg)]:max-w-none tw:[.markdown-preview_&]:pl-0`,
  overlayActions: String.raw`tw:[&_.button+.button]:ml-[var(--spacing-m)] tw:[&_:is(.button-surface--link,.tab,.footer\_\_link,.button--uri-indicator,[data-comment-time],.comment\_\_action)]:align-middle tw:[&_.markdown-preview_a]:align-middle tw:[.markdown-preview_&_a]:align-middle tw:[.file-viewer--ended-embed_&_a:first-of-type]:mr-[var(--spacing-s)]`,
} as const;
