export const PUBLISH_FORM_FIELD_CALENDAR_CLASS =
  'tw:mb-app-xs tw:ml-[calc(var(--spacing-xs)*-1)] tw:rounded-app tw:border tw:border-app-border tw:[animation:menu-animate-in_var(--animation-duration)_var(--animation-style)] tw:[box-shadow:3px_3px_rgba(0,0,0,0.1)]';

export const PUBLISH_DATE_PICKER_INPUT_CLASS = String.raw`date-picker-input tw:z-[9] tw:h-[var(--height-input)] tw:rounded-app tw:bg-[var(--color-input-bg)] tw:px-app-s tw:font-bold tw:text-app-text tw:placeholder:text-[var(--color-input-placeholder)] tw:placeholder:opacity-40 tw:disabled:opacity-40 tw:[&[type='range']]:h-[0.5rem] tw:[&[type='range']]:bg-app-secondary tw:[&_.react-datetime-picker\_\_wrapper]:[border:0] tw:[&_.react-datetime-picker\_\_wrapper_input]:bg-[unset]`;

export const PUBLISH_FORM_FIELD_DATE_PICKER_CLASS = [
  String.raw`form-field-date-picker tw:[font-size:var(--font-base)] tw:[&_:is(label,.confirm\_\_label)]:mt-0 tw:[&_:is(label,.confirm\_\_label)]:block`,
  String.raw`tw:[&_.react-datetime-picker\_\_button_svg]:stroke-app-text tw:[&_.react-datetime-picker\_\_button:enabled:hover_.react-datetime-picker\_\_button\_\_icon]:stroke-app-primary tw:[&_.react-datetime-picker\_\_button:enabled:focus_.react-datetime-picker\_\_button\_\_icon]:stroke-app-primary tw:[&_.react-date-picker\_\_calendar]:z-[1000]`,
  String.raw`tw:[&_.react-calendar]:w-[350px] tw:[&_.react-calendar]:max-w-full tw:[&_.react-calendar]:border tw:[&_.react-calendar]:border-[#a0a096] tw:[&_.react-calendar]:[background:var(--color-card-background)] tw:[&_.react-calendar]:[font-family:inherit] tw:[&_.react-calendar]:leading-none`,
  String.raw`tw:[&_.react-calendar--doubleView]:w-[700px] tw:[&_.react-calendar--doubleView_.react-calendar\_\_viewContainer]:m-[-0.5em] tw:[&_.react-calendar--doubleView_.react-calendar\_\_viewContainer]:flex tw:[&_.react-calendar--doubleView_.react-calendar\_\_viewContainer_>*]:m-[0.5em] tw:[&_.react-calendar--doubleView_.react-calendar\_\_viewContainer_>*]:w-1/2`,
  String.raw`tw:[&_.react-calendar]:box-border tw:[&_.react-calendar]:[padding:2px_1px] tw:[&_.react-calendar_*]:box-border tw:[&_.react-calendar_*]:[padding:2px_1px] tw:[&_.react-calendar_*::before]:box-border tw:[&_.react-calendar_*::before]:[padding:2px_1px] tw:[&_.react-calendar_*::after]:box-border tw:[&_.react-calendar_*::after]:[padding:2px_1px]`,
  String.raw`tw:[&_.react-calendar_button]:m-0 tw:[&_.react-calendar_button]:[border:0] tw:[&_.react-calendar_button]:outline-none tw:[&_.react-calendar_button:enabled:hover]:cursor-pointer tw:[&_.react-calendar_button:disabled]:bg-[rgba(var(--color-header-background-base),1)]`,
  String.raw`tw:[&_.react-calendar\_\_navigation]:mb-[1em] tw:[&_.react-calendar\_\_navigation]:h-[44px] tw:[&_.react-calendar\_\_navigation]:text-app-text tw:[&_.react-calendar\_\_navigation\_\_label]:text-app-text tw:[&_.react-calendar\_\_navigation_button]:min-w-[44px] tw:[&_.react-calendar\_\_navigation_button]:[background:none] tw:[&_.react-calendar\_\_navigation_button]:text-app-text tw:[&_.react-calendar\_\_navigation_button:enabled:hover]:bg-[var(--color-button-alt-bg-hover)] tw:[&_.react-calendar\_\_navigation_button:enabled:focus]:bg-[var(--color-button-alt-bg-hover)] tw:[&_.react-calendar\_\_navigation_button[disabled]]:text-app-text`,
  String.raw`tw:[&_.react-calendar\_\_month-view\_\_weekdays]:text-center tw:[&_.react-calendar\_\_month-view\_\_weekdays]:text-[0.75em] tw:[&_.react-calendar\_\_month-view\_\_weekdays]:font-bold tw:[&_.react-calendar\_\_month-view\_\_weekdays]:text-[var(--color-text-alt)] tw:[&_.react-calendar\_\_month-view\_\_weekdays]:uppercase tw:[&_.react-calendar\_\_month-view\_\_weekdays\_\_weekday]:p-[0.5em] tw:[&_.react-calendar\_\_month-view\_\_weekNumbers]:font-bold tw:[&_.react-calendar\_\_month-view\_\_weekNumbers_.react-calendar\_\_tile]:flex tw:[&_.react-calendar\_\_month-view\_\_weekNumbers_.react-calendar\_\_tile]:items-center tw:[&_.react-calendar\_\_month-view\_\_weekNumbers_.react-calendar\_\_tile]:justify-center tw:[&_.react-calendar\_\_month-view\_\_weekNumbers_.react-calendar\_\_tile]:p-[1em_0.6666666667em] tw:[&_.react-calendar\_\_month-view\_\_weekNumbers_.react-calendar\_\_tile]:text-[0.75em]`,
  String.raw`tw:[&_:is(.react-calendar\_\_month-view\_\_days\_\_day,.react-calendar\_\_month-view\_\_days\_\_day--weekend)]:font-normal tw:[&_:is(.react-calendar\_\_month-view\_\_days\_\_day,.react-calendar\_\_month-view\_\_days\_\_day--weekend)]:text-app-text tw:[&_:is(.react-calendar\_\_year-view,.react-calendar\_\_decade-view,.react-calendar\_\_century-view)_.react-calendar\_\_tile]:p-[2em_0.5em]`,
  String.raw`tw:[&_.react-calendar\_\_tile]:max-w-full tw:[&_.react-calendar\_\_tile]:rounded-app tw:[&_.react-calendar\_\_tile]:[background:none] tw:[&_.react-calendar\_\_tile]:p-[0.75em_0.5em] tw:[&_.react-calendar\_\_tile]:text-center tw:[&_.react-calendar\_\_tile]:text-app-text tw:[&_.react-calendar\_\_tile:enabled:hover]:bg-[var(--color-button-alt-bg-hover)] tw:[&_.react-calendar\_\_tile:enabled:hover]:text-app-primary-contrast tw:[&_.react-calendar\_\_tile:enabled:focus]:bg-[var(--color-button-alt-bg-hover)] tw:[&_.react-calendar\_\_tile:enabled:focus]:text-app-primary-contrast tw:[&_.react-calendar\_\_tile:disabled]:bg-[rgba(var(--color-primary-dynamic),0.4)]`,
  String.raw`tw:[&_.react-calendar\_\_tile--now]:bg-[var(--color-button-secondary-bg)] tw:[&_.react-calendar\_\_tile--now:enabled:hover]:bg-[var(--color-button-secondary-bg-hover)] tw:[&_.react-calendar\_\_tile--now:enabled:focus]:bg-[var(--color-button-secondary-bg-hover)] tw:[&_.react-calendar\_\_tile--hasActive]:bg-[var(--color-button-primary-bg)] tw:[&_.react-calendar\_\_tile--hasActive]:text-[var(--color-button-primary-text)] tw:[&_.react-calendar\_\_tile--hasActive:enabled:hover]:bg-[var(--color-button-primary-bg-hover)] tw:[&_.react-calendar\_\_tile--hasActive:enabled:focus]:bg-[var(--color-button-primary-bg-hover)] tw:[&_.react-calendar\_\_tile--active]:bg-[var(--color-button-primary-bg)] tw:[&_.react-calendar\_\_tile--active]:text-[var(--color-button-primary-text)] tw:[&_.react-calendar\_\_tile--active:enabled:hover]:bg-[var(--color-button-primary-bg-hover)] tw:[&_.react-calendar\_\_tile--active:enabled:focus]:bg-[var(--color-button-primary-bg-hover)]`,
  String.raw`tw:[&_.react-calendar--selectRange_.react-calendar\_\_tile--hover]:bg-[#e6e6e6] tw:[&_.react-datetime-picker\_\_inputGroup\_\_leadingZero]:mb-[1px] tw:[&_.react-datetime-picker\_\_inputGroup\_\_input--hasLeadingZero]:ml-[-0.54em] tw:[&_.react-datetime-picker\_\_inputGroup\_\_input--hasLeadingZero]:pl-[calc(1px+0.54em)] tw:[&_.react-calendar\_\_month-view\_\_days\_\_day--neighboringMonth]:!text-[var(--color-gray-5)]`,
  String.raw`tw:[&_.react-datepicker]:border tw:[&_.react-datepicker]:border-app-border tw:[&_.react-datepicker]:bg-app-card tw:[&_.react-datepicker]:text-app-text tw:[&_.react-datepicker]:[font-family:inherit] tw:[&_.react-datepicker\_\_header]:border-b tw:[&_.react-datepicker\_\_header]:border-b-app-border tw:[&_.react-datepicker\_\_header]:bg-[var(--color-header-button)] tw:[&_:is(.react-datepicker\_\_current-month,.react-datepicker-time\_\_header,.react-datepicker\_\_day-name)]:text-app-text`,
  String.raw`tw:[&_.react-datepicker\_\_day]:text-app-text tw:[&_.react-datepicker\_\_day:hover]:bg-[var(--color-button-alt-bg-hover)] tw:[&_:is(.react-datepicker\_\_day--selected,.react-datepicker\_\_day--keyboard-selected)]:bg-[var(--color-button-primary-bg)] tw:[&_:is(.react-datepicker\_\_day--selected,.react-datepicker\_\_day--keyboard-selected)]:text-app-primary-contrast tw:[&_.react-datepicker\_\_day--selected:hover]:bg-[var(--color-button-primary-bg-hover)] tw:[&_.react-datepicker\_\_day--keyboard-selected:hover]:bg-[var(--color-button-primary-bg-hover)] tw:[&_.react-datepicker\_\_day--disabled]:text-app-text-subtitle tw:[&_.react-datepicker\_\_day--outside-month]:text-[var(--color-gray-5)]`,
  String.raw`tw:[&_.react-datepicker\_\_navigation-icon::before]:border-[var(--color-text-subtitle)] tw:[&_.react-datepicker\_\_triangle]:hidden tw:[&_.react-datepicker-popper]:z-[1000] tw:[&_.react-datepicker\_\_time-container]:border-l tw:[&_.react-datepicker\_\_time-container]:border-l-app-border tw:[&_.react-datepicker\_\_time]:bg-app-card tw:[&_.react-datepicker\_\_time]:text-app-text tw:[&_.react-datepicker\_\_time-list-item]:ml-0 tw:[&_.react-datepicker\_\_time-list-item:hover]:!bg-[var(--color-button-alt-bg-hover)] tw:[&_.react-datepicker\_\_time-list-item--selected]:!bg-[var(--color-button-primary-bg)] tw:[&_.react-datepicker\_\_time-list-item--selected]:!text-app-primary-contrast`,
].join(' ');

export const PUBLISH_FORM_FIELD_DATE_PICKER_CONTROLS_CLASS = String.raw`form-field-date-picker__controls tw:flex tw:[&_:is(.date-picker-input,.button-surface--link,.tab,.button--uri-indicator,[data-comment-time],.comment\_\_action,.footer\_\_link)]:mr-app-m tw:[&_.markdown-preview_a]:mr-app-m tw:[.markdown-preview_&_a]:mr-app-m`;

export const PUBLISH_FORM_FIELD_DATE_PICKER_ERROR_CLASS = String.raw`form-field-date-picker__error tw:self-center tw:text-app-text-error tw:[&_span]:mr-app-xs`;

export const PUBLISH_VISIBILITY_SCHEDULED_CLASS = String.raw`publish-visibility-scheduled-surface tw:mt-app-s tw:[&_:is(input,select)]:![background:rgba(var(--color-text-base),0.06)] tw:[&_label::before]:!bg-[rgba(var(--color-text-base),0.06)] tw:[&_.form-field-date-picker]:mt-app-xs tw:upto-small:[&_.form-field-date-picker\_\_controls]:flex-wrap`;
