export const CLAIM_COVER_CLASSES = {
  base: String.raw`tw:relative tw:flex tw:max-h-full tw:items-center tw:justify-center tw:rounded-app tw:bg-center tw:bg-no-repeat tw:bg-[length:100%] tw:hover:cursor-pointer tw:before:float-left tw:before:pt-[var(--aspect-ratio-standard)] tw:before:content-[''] tw:after:block tw:after:clear-both tw:after:content-[''] tw:[&_.button-surface--play]:hidden tw:[&:fullscreen]:size-full tw:[&:not([data-claim-cover-shorts])>*:not([data-claim-cover-live-image]):not([data-file-viewer-embedded-header])]:relative tw:[&:not([data-claim-cover-shorts])>*:not([data-claim-cover-live-image]):not([data-file-viewer-embedded-header])]:z-[1] tw:[.file-page\_\_video-container_&]:size-full tw:[.file-page\_\_video-container_&]:max-h-[var(--desktop-portrait-player-max-height)] tw:[[data-embed-wrapper]_&]:!rounded-none`,
  nonEmbed: 'tw:m-auto tw:upto-small:m-0 tw:upto-small:rounded-none tw:upto-small:border-none',
  embed: 'tw:h-full',
  theater: 'tw:h-full tw:!max-h-[var(--desktop-portrait-player-max-height)] tw:!rounded-none',
  shorts: String.raw`tw:[:is(.shorts-page,.main--shorts-page)_&]:fixed tw:[:is(.shorts-page,.main--shorts-page)_&]:!top-0 tw:[:is(.shorts-page,.main--shorts-page)_&]:!left-[var(--claim-cover-shorts-left,50%)] tw:[:is(.shorts-page,.main--shorts-page)_&]:!z-[2] tw:[:is(.shorts-page,.main--shorts-page)_&]:!h-[90vh] tw:[:is(.shorts-page,.main--shorts-page)_&]:!max-h-[90vh] tw:[:is(.shorts-page,.main--shorts-page)_&]:!w-[var(--shorts-viewer-width,var(--shorts-viewer-width-default))] tw:[:is(.shorts-page,.main--shorts-page)_&]:overflow-hidden tw:[:is(.shorts-page,.main--shorts-page)_&]:!rounded-[10px] tw:[:is(.shorts-page,.main--shorts-page)_&]:border-none tw:[:is(.shorts-page,.main--shorts-page)_&]:aspect-[9/16] tw:[:is(.shorts-page,.main--shorts-page)_&]:!bg-cover tw:[:is(.shorts-page,.main--shorts-page)_&]:!bg-center tw:[:is(.shorts-page,.main--shorts-page)_&]:![margin:60px_0_0] tw:[:is(.shorts-page,.main--shorts-page)_&]:![transform:var(--claim-cover-shorts-transform,translate(calc(-50%_-_6px),0%))] tw:[:is(.shorts-page,.main--shorts-page)_&]:![transition:all_0.3s_cubic-bezier(0.4,0,0.2,1)] tw:[:is(.shorts-page,.main--shorts-page)_&_.button-surface--play]:!block tw:[@media(max-width:1020px)]:[--claim-cover-shorts-left:0px] tw:[@media(max-width:1020px)]:[--claim-cover-shorts-transform:none] tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:fixed tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!top-0 tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!z-[2] tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!h-[100svh] tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!max-h-[100svh] tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!w-screen tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:overflow-hidden tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!rounded-none tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:object-cover tw:[@media(max-width:1020px)]:[:is(.shorts-page,.main--shorts-page)_&]:!mt-0 tw:[@media(min-width:1600px)]:[:is(.shorts-page,.main--shorts-page)_&]:!w-[var(--shorts-viewer-width,var(--shorts-viewer-width-default))] tw:[@media(min-width:1020px)_and_(max-width:1380px)_and_(max-height:860px)]:[:is(.shorts-page,.main--shorts-page)_&]:!w-[350px]`,
  sidePanel: String.raw`tw:[--claim-cover-shorts-transform:translate(-130%,0%)] tw:[@media(max-width:1020px)]:[--claim-cover-shorts-transform:none] tw:[@media(min-width:1020px)_and_(max-width:1400px)]:[--claim-cover-shorts-left:20px] tw:[@media(min-width:1020px)_and_(max-width:1400px)]:[--claim-cover-shorts-transform:none]`,
} as const;

export const CLAIM_COVER_SHORTS_SELECTOR = '[data-claim-cover-shorts]';

export const CLAIM_COVER_DISABLED_CLASS = 'tw:hover:!cursor-default';

export const CLAIM_COVER_BLACK_BACKGROUND_CLASS = String.raw`tw:[&:not(.card\_\_media--nsfw)]:bg-black`;

export const CLAIM_COVER_LINK_CLASS = String.raw`tw:[&>.button-surface\_\_content]:w-full tw:[&>.button-surface\_\_content_[data-protected-content-overlay]]:relative`;

export const CLAIM_COVER_LIVE_REFRESHING_CLASS = String.raw`tw:[&_.button-surface--play]:pointer-events-none tw:[&_.button-surface--play]:!opacity-0 tw:[&_.button-surface--play]:[transition:opacity_0.15s_ease]`;

export const CLAIM_COVER_LIVE_IMAGE_CLASS =
  'tw:pointer-events-none tw:absolute tw:inset-0 tw:z-0 tw:size-full tw:object-cover tw:opacity-0 tw:[will-change:opacity] tw:[transition:opacity_0.22s_ease-out]';
